"""Bitmaps, generated by tools/bitmaps.py. Do not edit.

Source: assets/sprites, assets/tiles. Regenerate with::

    python tools/bitmaps.py --python <this file> assets/sprites assets/tiles

Bit 7 is the leftmost pixel, rows top to bottom -- the Spectrum's
own order, which is what `core.Screen` models. A row is one byte,
or a tuple of two for the 16-wide class, left cell first.

There is no timestamp here on purpose: this file is committed, and a
test regenerates it and compares byte for byte, so any diff at all is
art and code having drifted.
"""

BATTEN = (
    0x00,  # ........   a strip light seen from above, not an octagon
    0x00,  # ........
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x00,  # ........
    0x00,  # ........
)

BODY = (
    (0x03, 0x00),  # ......##........   the arm, flung back over the head
    (0x3D, 0x00),  # ..####.#........
    (0x7E, 0xF0),  # .######.####....   the head, off the axis, and a shoulder
    (0x7D, 0xFF),  # .#####.#########   the trunk, lying across the join
    (0x3B, 0xFF),  # ..###.##########
    (0x03, 0xDC),  # ......####.###..   hips, and one leg trailing
    (0x00, 0x63),  # .........##...##   the other leg, splayed differently
    (0x00, 0x00),  # ................
)

CLEG_A = (
    0x00,  # ........
    0x42,  # .#....#.   wings down
    0x24,  # ..#..#..
    0x7E,  # .######.   body
    0xFF,  # ########
    0x7E,  # .######.
    0x24,  # ..#..#..   legs
    0x42,  # .#....#.
)

CLEG_B = (
    0x00,  # ........
    0x00,  # ........   wings up: same body, same ink count
    0x66,  # .##..##.
    0x7E,  # .######.   body
    0xFF,  # ########
    0x7E,  # .######.
    0x66,  # .##..##.   legs
    0x00,  # ........
)

DOORWAY_00 = (
    0x00,  # ........   mask  0, -
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

DOORWAY_01 = (
    0xC3,  # ##....##   mask  1, N
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

DOORWAY_02 = (
    0x01,  # .......#   mask  2, E
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0x01,  # .......#
)

DOORWAY_03 = (
    0xC3,  # ##....##   mask  3, NE
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0x01,  # .......#
)

DOORWAY_04 = (
    0x00,  # ........   mask  4, S
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xC3,  # ##....##
)

DOORWAY_05 = (
    0xC3,  # ##....##   mask  5, NS
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xC3,  # ##....##
)

DOORWAY_06 = (
    0x01,  # .......#   mask  6, ES
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0xC3,  # ##....##
)

DOORWAY_07 = (
    0xC3,  # ##....##   mask  7, NES
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0xC3,  # ##....##
)

DOORWAY_08 = (
    0x80,  # #.......   mask  8, W
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0x80,  # #.......
)

DOORWAY_09 = (
    0xC3,  # ##....##   mask  9, NW
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0x80,  # #.......
)

DOORWAY_10 = (
    0x81,  # #......#   mask 10, EW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0x81,  # #......#
)

DOORWAY_11 = (
    0xC3,  # ##....##   mask 11, NEW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0x81,  # #......#
)

DOORWAY_12 = (
    0x80,  # #.......   mask 12, SW
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0xC3,  # ##....##
)

DOORWAY_13 = (
    0xC3,  # ##....##   mask 13, NSW
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0xC3,  # ##....##
)

DOORWAY_14 = (
    0x81,  # #......#   mask 14, ESW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0xC3,  # ##....##
)

DOORWAY_15 = (
    0xC3,  # ##....##   mask 15, NESW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0xC3,  # ##....##
)

DOOR_LOCKED = (
    0xFF,  # ########   a closed frame
    0x81,  # #......#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xA5,  # #.#..#.#   the keyhole
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0x81,  # #......#
    0xFF,  # ########
)

DOOR_OPEN = (
    0xC3,  # ##....##   two jambs, a four-pixel gap
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##   no head and no sill: open at both ends
)

FLOOR_DIM = (
    0x00,  # ........   one dot in sixty-four -- ground you are remembering, not seeing
    0x00,  # ........
    0x00,  # ........
    0x10,  # ...#....
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_LIT = (
    0x00,  # ........   four dots, evenly spread -- fully lit ground
    0x44,  # .#...#..
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x44,  # .#...#..
    0x00,  # ........
    0x00,  # ........
)

FOLLOWER = (
    0x00,  # ........
    0x00,  # ........
    0x3C,  # ..####..   head
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x7E,  # .######.   shoulders
    0x7E,  # .######.
    0x5A,  # .#.##.#.   arms down at the sides
    0x5A,  # .#.##.#.
    0x5A,  # .#.##.#.
    0x3C,  # ..####..   hips
    0x24,  # ..#..#..   legs
    0x24,  # ..#..#..
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

HOUSING = (
    0x3C,  # ..####..   a ring with a lens: the searchlight, bolted down
    0x42,  # .#....#.
    0x81,  # #......#
    0x99,  # #..##..#
    0x99,  # #..##..#
    0x81,  # #......#
    0x42,  # .#....#.
    0x3C,  # ..####..
)

KEY = (
    0x00,  # ........
    0x1C,  # ...###..   ring
    0x22,  # ..#...#.
    0x22,  # ..#...#.
    0x1C,  # ...###..
    0x08,  # ....#...   shaft
    0x0E,  # ....###.   teeth
    0x00,  # ........
)

LAMP_OFF = (
    0x3C,  # ..####..   a hollow octagon: a spotlight lying dark
    0x42,  # .#....#.
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x42,  # .#....#.
    0x3C,  # ..####..
)

LAMP_ON = (
    0x3C,  # ..####..   filled: the same spotlight burning
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x7E,  # .######.
    0x3C,  # ..####..
)

NEST = (
    0x00,  # ........
    0x30,  # ..##....   the lip, broken and off-centre
    0x7C,  # .#####..
    0xFE,  # #######.
    0xDF,  # ##.#####   the brood, uneven
    0xFF,  # ########
    0x7E,  # .######.
    0x2C,  # ..#.##..   it does not sit square
)

PLAYER = (
    0x00,  # ........
    0x3C,  # ..####..   the lamp, worn on the helmet
    0x3C,  # ..####..
    0x7E,  # .######.   head, seen from above - no hat, no face
    0x7E,  # .######.
    0xFF,  # ########   shoulders, full width - the kit
    0xFF,  # ########
    0xDB,  # ##.##.##   arms clear of the body
    0xDB,  # ##.##.##
    0xDB,  # ##.##.##
    0x7E,  # .######.   hips
    0x66,  # .##..##.   legs, planted wide
    0x66,  # .##..##.
    0x00,  # ........   one clear row, so the mark is not feet
    0xFF,  # ########   the mark: the only figure with ground under him
    0xFF,  # ########
)

SPRAY = (
    0x00,  # ........   scattered droplets, staggered so they are not the floor's columns
    0x22,  # ..#...#.
    0x00,  # ........
    0x88,  # #...#...
    0x00,  # ........
    0x22,  # ..#...#.
    0x00,  # ........
    0x88,  # #...#...
)

WALL_DIM_00 = (
    0xFF,  # ########   mask  0, -
    0xFF,  # ########
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xFF,  # ########
    0xFF,  # ########
)

WALL_DIM_01 = (
    0x81,  # #......#   mask  1, N
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0xFF,  # ########
)

WALL_DIM_02 = (
    0xFF,  # ########   mask  2, E
    0xC0,  # ##......
    0xC0,  # ##......
    0xC0,  # ##......
    0xC0,  # ##......
    0xC0,  # ##......
    0xC0,  # ##......
    0xFF,  # ########
)

WALL_DIM_03 = (
    0x80,  # #.......   mask  3, NE
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0xFF,  # ########
)

WALL_DIM_04 = (
    0xFF,  # ########   mask  4, S
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
)

WALL_DIM_05 = (
    0x81,  # #......#   mask  5, NS
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
)

WALL_DIM_06 = (
    0xFF,  # ########   mask  6, ES
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
)

WALL_DIM_07 = (
    0x80,  # #.......   mask  7, NES
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
)

WALL_DIM_08 = (
    0xFF,  # ########   mask  8, W
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0xFF,  # ########
)

WALL_DIM_09 = (
    0x01,  # .......#   mask  9, NW
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
)

WALL_DIM_10 = (
    0xFF,  # ########   mask 10, EW
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xFF,  # ########
)

WALL_DIM_11 = (
    0x00,  # ........   mask 11, NEW
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xFF,  # ########
)

WALL_DIM_12 = (
    0xFF,  # ########   mask 12, SW
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
)

WALL_DIM_13 = (
    0x01,  # .......#   mask 13, NSW
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
)

WALL_DIM_14 = (
    0xFF,  # ########   mask 14, ESW
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

WALL_DIM_15 = (
    0x00,  # ........   mask 15, NESW
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

WALL_LIT_00 = (
    0xFF,  # ########   mask  0, -
    0xFF,  # ########
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

WALL_LIT_01 = (
    0x91,  # #..#...#   mask  1, N
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

WALL_LIT_02 = (
    0xFF,  # ########   mask  2, E
    0xFF,  # ########
    0xC1,  # ##.....#
    0xC1,  # ##.....#
    0xC1,  # ##.....#
    0xFF,  # ########
    0xD0,  # ##.#....
    0xFF,  # ########
)

WALL_LIT_03 = (
    0x90,  # #..#....   mask  3, NE
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x90,  # #..#....
    0xFF,  # ########
)

WALL_LIT_04 = (
    0xFF,  # ########   mask  4, S
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x91,  # #..#...#
    0x91,  # #..#...#
)

WALL_LIT_05 = (
    0x91,  # #..#...#   mask  5, NS
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x91,  # #..#...#
    0x91,  # #..#...#
)

WALL_LIT_06 = (
    0xFF,  # ########   mask  6, ES
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x90,  # #..#....
    0x90,  # #..#....
)

WALL_LIT_07 = (
    0x90,  # #..#....   mask  7, NES
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x90,  # #..#....
    0x90,  # #..#....
)

WALL_LIT_08 = (
    0xFF,  # ########   mask  8, W
    0xFF,  # ########
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0xFF,  # ########
    0x13,  # ...#..##
    0xFF,  # ########
)

WALL_LIT_09 = (
    0x11,  # ...#...#   mask  9, NW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x11,  # ...#...#
    0xFF,  # ########
)

WALL_LIT_10 = (
    0xFF,  # ########   mask 10, EW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0xFF,  # ########
)

WALL_LIT_11 = (
    0x10,  # ...#....   mask 11, NEW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0xFF,  # ########
)

WALL_LIT_12 = (
    0xFF,  # ########   mask 12, SW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x11,  # ...#...#
    0x11,  # ...#...#
)

WALL_LIT_13 = (
    0x11,  # ...#...#   mask 13, NSW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x11,  # ...#...#
    0x11,  # ...#...#
)

WALL_LIT_14 = (
    0xFF,  # ########   mask 14, ESW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0x10,  # ...#....
)

WALL_LIT_15 = (
    0x10,  # ...#....   mask 15, NESW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0x10,  # ...#....
)

WORKER = (
    0x00,  # ........
    0x00,  # ........
    0xC3,  # ##....##   hands, raised clear of the shoulders
    0xC3,  # ##....##
    0x99,  # #..##..#   arms, and the crown of the head between them
    0xBD,  # #.####.#   head
    0x7E,  # .######.   shoulders - narrower than the player's
    0x7E,  # .######.
    0x3C,  # ..####..   trunk
    0x3C,  # ..####..
    0x24,  # ..#..#..   legs, foreshortened
    0x24,  # ..#..#..
    0x24,  # ..#..#..
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

#: Every bitmap by name, for the tools and tests that want to
#: walk them all.
BITMAPS = {
    "BATTEN": BATTEN,
    "BODY": BODY,
    "CLEG_A": CLEG_A,
    "CLEG_B": CLEG_B,
    "DOORWAY_00": DOORWAY_00,
    "DOORWAY_01": DOORWAY_01,
    "DOORWAY_02": DOORWAY_02,
    "DOORWAY_03": DOORWAY_03,
    "DOORWAY_04": DOORWAY_04,
    "DOORWAY_05": DOORWAY_05,
    "DOORWAY_06": DOORWAY_06,
    "DOORWAY_07": DOORWAY_07,
    "DOORWAY_08": DOORWAY_08,
    "DOORWAY_09": DOORWAY_09,
    "DOORWAY_10": DOORWAY_10,
    "DOORWAY_11": DOORWAY_11,
    "DOORWAY_12": DOORWAY_12,
    "DOORWAY_13": DOORWAY_13,
    "DOORWAY_14": DOORWAY_14,
    "DOORWAY_15": DOORWAY_15,
    "DOOR_LOCKED": DOOR_LOCKED,
    "DOOR_OPEN": DOOR_OPEN,
    "FLOOR_DIM": FLOOR_DIM,
    "FLOOR_LIT": FLOOR_LIT,
    "FOLLOWER": FOLLOWER,
    "HOUSING": HOUSING,
    "KEY": KEY,
    "LAMP_OFF": LAMP_OFF,
    "LAMP_ON": LAMP_ON,
    "NEST": NEST,
    "PLAYER": PLAYER,
    "SPRAY": SPRAY,
    "WALL_DIM_00": WALL_DIM_00,
    "WALL_DIM_01": WALL_DIM_01,
    "WALL_DIM_02": WALL_DIM_02,
    "WALL_DIM_03": WALL_DIM_03,
    "WALL_DIM_04": WALL_DIM_04,
    "WALL_DIM_05": WALL_DIM_05,
    "WALL_DIM_06": WALL_DIM_06,
    "WALL_DIM_07": WALL_DIM_07,
    "WALL_DIM_08": WALL_DIM_08,
    "WALL_DIM_09": WALL_DIM_09,
    "WALL_DIM_10": WALL_DIM_10,
    "WALL_DIM_11": WALL_DIM_11,
    "WALL_DIM_12": WALL_DIM_12,
    "WALL_DIM_13": WALL_DIM_13,
    "WALL_DIM_14": WALL_DIM_14,
    "WALL_DIM_15": WALL_DIM_15,
    "WALL_LIT_00": WALL_LIT_00,
    "WALL_LIT_01": WALL_LIT_01,
    "WALL_LIT_02": WALL_LIT_02,
    "WALL_LIT_03": WALL_LIT_03,
    "WALL_LIT_04": WALL_LIT_04,
    "WALL_LIT_05": WALL_LIT_05,
    "WALL_LIT_06": WALL_LIT_06,
    "WALL_LIT_07": WALL_LIT_07,
    "WALL_LIT_08": WALL_LIT_08,
    "WALL_LIT_09": WALL_LIT_09,
    "WALL_LIT_10": WALL_LIT_10,
    "WALL_LIT_11": WALL_LIT_11,
    "WALL_LIT_12": WALL_LIT_12,
    "WALL_LIT_13": WALL_LIT_13,
    "WALL_LIT_14": WALL_LIT_14,
    "WALL_LIT_15": WALL_LIT_15,
    "WORKER": WORKER,
}
