"""Bitmaps, generated by tools/bitmaps.py. Do not edit.

Source: assets/sprites, assets/tiles. Regenerate with::

    python tools/bitmaps.py --python <this file> assets/sprites assets/tiles

Bit 7 is the leftmost pixel, rows top to bottom -- the Spectrum's
own order, which is what `core.Screen` models. A row is one byte,
or a tuple of two for the 16-wide class, left cell first.

Every sprite has a `NAME_MASK` beside it, collected in `MASKS`: its
ink dilated one pixel and clipped to the box, derived by the tool and
never drawn by hand. A set bit is a pixel to clear before the ink is
set. Tiles have none; they composite by OR.

There is no timestamp here on purpose: this file is committed, and a
test regenerates it and compares byte for byte, so any diff at all is
art and code having drifted.
"""

BATTEN = (
    0x00,  # ........   a strip light seen from above, not an octagon
    0x00,  # ........
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x00,  # ........
    0x00,  # ........
)

#: BATTEN's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
BATTEN_MASK = (
    0x00,  # ........
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x00,  # ........
)

BODY = (
    (0x03, 0x00),  # ......##........   the arm, flung back over the head
    (0x3D, 0x00),  # ..####.#........
    (0x7E, 0xF0),  # .######.####....   the head, off the axis, and a shoulder
    (0x7D, 0xFF),  # .#####.#########   the trunk, lying across the join
    (0x3B, 0xFF),  # ..###.##########
    (0x03, 0xDC),  # ......####.###..   hips, and one leg trailing
    (0x00, 0x63),  # .........##...##   the other leg, splayed differently
    (0x00, 0x00),  # ................
)

#: BODY's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
BODY_MASK = (
    (0x7F, 0x80),  # .########.......
    (0xFF, 0xF8),  # #############...
    (0xFF, 0xFF),  # ################
    (0xFF, 0xFF),  # ################
    (0xFF, 0xFF),  # ################
    (0x7F, 0xFF),  # .###############
    (0x07, 0xFF),  # .....###########
    (0x00, 0xF7),  # ........####.###
)

CABINET = (
    0xFF,  # ########   a filing cabinet from above: three drawer fronts
    0x81,  # #......#
    0xBD,  # #.####.#
    0x81,  # #......#
    0xBD,  # #.####.#
    0x81,  # #......#
    0xBD,  # #.####.#
    0xFF,  # ########
)

CLEG_A = (
    0x00,  # ........
    0x18,  # ...##...   head
    0xFF,  # ########   wings out, the whole width
    0xFF,  # ########
    0x18,  # ...##...   body
    0x18,  # ...##...
    0x18,  # ...##...
    0x42,  # .#....#.   legs
)

#: CLEG_A's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
CLEG_A_MASK = (
    0x3C,  # ..####..
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x3C,  # ..####..
    0xFF,  # ########
    0xFF,  # ########
)

CLEG_B = (
    0x00,  # ........
    0x18,  # ...##...   head, unchanged
    0x3C,  # ..####..   thorax, the wing roots
    0x5A,  # .#.##.#.   wings swept back along the body
    0x5A,  # .#.##.#.
    0x99,  # #..##..#
    0x81,  # #......#   wingtips, past the abdomen
    0x24,  # ..#..#..   legs, tucked
)

#: CLEG_B's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
CLEG_B_MASK = (
    0x3C,  # ..####..
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

CLEG_M = (
    0x00,  # ........
    0x18,  # ...##...   head, unchanged
    0x66,  # .##..##.   wings half swept, clear of the body
    0x3C,  # ..####..   the roots, as in B
    0x18,  # ...##...   body
    0x18,  # ...##...
    0x99,  # #..##..#   wingtips, level with the abdomen
    0x42,  # .#....#.   legs, as in A
)

#: CLEG_M's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
CLEG_M_MASK = (
    0x3C,  # ..####..
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

CRATE = (
    0xFF,  # ########   a crate from above: a box with its lid nailed across the diagonals
    0x81,  # #......#
    0xA5,  # #.#..#.#
    0x99,  # #..##..#
    0x99,  # #..##..#
    0xA5,  # #.#..#.#
    0x81,  # #......#
    0xFF,  # ########
)

DESK_L = (
    0xFF,  # ########   the left half of a desk: the top, with a blotter on it
    0x81,  # #......#
    0xBD,  # #.####.#
    0xA5,  # #.#..#.#
    0xBD,  # #.####.#
    0x81,  # #......#
    0xFF,  # ########
    0x00,  # ........
)

DESK_R = (
    0xFF,  # ########   the right half of a desk: bare top
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x00,  # ........
)

DOORWAY_00 = (
    0x00,  # ........   mask  0, -
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

DOORWAY_01 = (
    0xC3,  # ##....##   mask  1, N
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

DOORWAY_02 = (
    0x01,  # .......#   mask  2, E
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0x01,  # .......#
)

DOORWAY_03 = (
    0xC3,  # ##....##   mask  3, NE
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0x01,  # .......#
)

DOORWAY_04 = (
    0x00,  # ........   mask  4, S
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xC3,  # ##....##
)

DOORWAY_05 = (
    0xC3,  # ##....##   mask  5, NS
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xC3,  # ##....##
)

DOORWAY_06 = (
    0x01,  # .......#   mask  6, ES
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0xC3,  # ##....##
)

DOORWAY_07 = (
    0xC3,  # ##....##   mask  7, NES
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0xC3,  # ##....##
)

DOORWAY_08 = (
    0x80,  # #.......   mask  8, W
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0x80,  # #.......
)

DOORWAY_09 = (
    0xC3,  # ##....##   mask  9, NW
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0x80,  # #.......
)

DOORWAY_10 = (
    0x81,  # #......#   mask 10, EW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0x81,  # #......#
)

DOORWAY_11 = (
    0xC3,  # ##....##   mask 11, NEW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0x81,  # #......#
)

DOORWAY_12 = (
    0x80,  # #.......   mask 12, SW
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0xC3,  # ##....##
)

DOORWAY_13 = (
    0xC3,  # ##....##   mask 13, NSW
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0xC3,  # ##....##
)

DOORWAY_14 = (
    0x81,  # #......#   mask 14, ESW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0xC3,  # ##....##
)

DOORWAY_15 = (
    0xC3,  # ##....##   mask 15, NESW
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x81,  # #......#
    0xC3,  # ##....##
)

DOOR_LOCKED = (
    0xFF,  # ########   a closed frame
    0x81,  # #......#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xA5,  # #.#..#.#   the keyhole
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0xBD,  # #.####.#
    0x81,  # #......#
    0xFF,  # ########
)

#: DOOR_LOCKED's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
DOOR_LOCKED_MASK = (
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

DOOR_OPEN = (
    0xC3,  # ##....##   two jambs, a four-pixel gap
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##   no head and no sill: open at both ends
)

#: DOOR_OPEN's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
DOOR_OPEN_MASK = (
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xE7,  # ###..###
)

FLOOR_DIM_00 = (
    0x20,  # ..#.....   cell 0: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_01 = (
    0x00,  # ........   cell 1: the first of its four lit dots, the rest cleared
    0x20,  # ..#.....
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_02 = (
    0x00,  # ........   cell 2: the first of its four lit dots, the rest cleared
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_03 = (
    0x04,  # .....#..   cell 3: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_04 = (
    0x20,  # ..#.....   cell 4: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_05 = (
    0x08,  # ....#...   cell 5: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_06 = (
    0x00,  # ........   cell 6: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x10,  # ...#....
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_07 = (
    0x20,  # ..#.....   cell 7: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_08 = (
    0x00,  # ........   cell 8: the first of its four lit dots, the rest cleared
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_09 = (
    0x00,  # ........   cell 9: the first of its four lit dots, the rest cleared
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_10 = (
    0x00,  # ........   cell 10: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_11 = (
    0x00,  # ........   cell 11: the first of its four lit dots, the rest cleared
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_12 = (
    0x00,  # ........   cell 12: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x10,  # ...#....
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_13 = (
    0x00,  # ........   cell 13: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x04,  # .....#..
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_14 = (
    0x40,  # .#......   cell 14: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_DIM_15 = (
    0x01,  # .......#   cell 15: the first of its four lit dots, the rest cleared
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_LIT_00 = (
    0x20,  # ..#.....   cell 0: four dots, cut from the tile above
    0x00,  # ........
    0x42,  # .#....#.
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x08,  # ....#...
    0x00,  # ........
)

FLOOR_LIT_01 = (
    0x00,  # ........   cell 1: four dots, cut from the tile above
    0x20,  # ..#.....
    0x00,  # ........
    0x80,  # #.......
    0x10,  # ...#....
    0x00,  # ........
    0x00,  # ........
    0x20,  # ..#.....
)

FLOOR_LIT_02 = (
    0x00,  # ........   cell 2: four dots, cut from the tile above
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
    0x01,  # .......#
    0x40,  # .#......
)

FLOOR_LIT_03 = (
    0x04,  # .....#..   cell 3: four dots, cut from the tile above
    0x00,  # ........
    0x21,  # ..#....#
    0x00,  # ........
    0x00,  # ........
    0x02,  # ......#.
    0x00,  # ........
    0x00,  # ........
)

FLOOR_LIT_04 = (
    0x22,  # ..#...#.   cell 4: four dots, cut from the tile above
    0x00,  # ........
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x10,  # ...#....
)

FLOOR_LIT_05 = (
    0x0A,  # ....#.#.   cell 5: four dots, cut from the tile above
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x80,  # #.......
)

FLOOR_LIT_06 = (
    0x00,  # ........   cell 6: four dots, cut from the tile above
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x14,  # ...#.#..
    0x00,  # ........
    0x24,  # ..#..#..
)

FLOOR_LIT_07 = (
    0x28,  # ..#.#...   cell 7: four dots, cut from the tile above
    0x00,  # ........
    0x40,  # .#......
    0x00,  # ........
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_LIT_08 = (
    0x00,  # ........   cell 8: four dots, cut from the tile above
    0x50,  # .#.#....
    0x00,  # ........
    0x00,  # ........
    0x10,  # ...#....
    0x00,  # ........
    0x00,  # ........
    0x02,  # ......#.
)

FLOOR_LIT_09 = (
    0x00,  # ........   cell 9: four dots, cut from the tile above
    0x40,  # .#......
    0x00,  # ........
    0x00,  # ........
    0x01,  # .......#
    0x08,  # ....#...
    0x01,  # .......#
    0x00,  # ........
)

FLOOR_LIT_10 = (
    0x00,  # ........   cell 10: four dots, cut from the tile above
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x50,  # .#.#....
    0x00,  # ........
    0x01,  # .......#
    0x10,  # ...#....
)

FLOOR_LIT_11 = (
    0x00,  # ........   cell 11: four dots, cut from the tile above
    0x50,  # .#.#....
    0x00,  # ........
    0x88,  # #...#...
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FLOOR_LIT_12 = (
    0x00,  # ........   cell 12: four dots, cut from the tile above
    0x00,  # ........
    0x10,  # ...#....
    0x00,  # ........
    0x20,  # ..#.....
    0x81,  # #......#
    0x00,  # ........
    0x00,  # ........
)

FLOOR_LIT_13 = (
    0x00,  # ........   cell 13: four dots, cut from the tile above
    0x00,  # ........
    0x04,  # .....#..
    0x40,  # .#......
    0x00,  # ........
    0x20,  # ..#.....
    0x00,  # ........
    0x10,  # ...#....
)

FLOOR_LIT_14 = (
    0x40,  # .#......   cell 14: four dots, cut from the tile above
    0x02,  # ......#.
    0x00,  # ........
    0x20,  # ..#.....
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x40,  # .#......
)

FLOOR_LIT_15 = (
    0x01,  # .......#   cell 15: four dots, cut from the tile above
    0x80,  # #.......
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x04,  # .....#..
    0x40,  # .#......
)

FOLLOWER_A = (
    0x00,  # ........
    0x00,  # ........
    0x18,  # ...##...   head, a disc
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x7E,  # .######.   shoulders
    0x7E,  # .######.
    0x58,  # .#.##...   hands beside the hips, swinging
    0x1A,  # ...##.#.
    0x0C,  # ....##..   feet
    0x30,  # ..##....
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

#: FOLLOWER_A's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
FOLLOWER_A_MASK = (
    0x00,  # ........
    0x3C,  # ..####..
    0x7E,  # .######.
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x7F,  # .#######
    0x7E,  # .######.
    0x78,  # .####...
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

FOLLOWER_B = (
    0x00,  # ........
    0x00,  # ........
    0x18,  # ...##...   head
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x7E,  # .######.   shoulders
    0x7E,  # .######.
    0x1A,  # ...##.#.   frame A in the mirror
    0x58,  # .#.##...
    0x30,  # ..##....   feet swapped
    0x0C,  # ....##..
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

#: FOLLOWER_B's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
FOLLOWER_B_MASK = (
    0x00,  # ........
    0x3C,  # ..####..
    0x7E,  # .######.
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFE,  # #######.
    0x7E,  # .######.
    0x1E,  # ...####.
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

GRATING = (
    0x00,  # ........   a grating, floor: a grille of dots, denser than the stipple
    0x54,  # .#.#.#..
    0x00,  # ........
    0x54,  # .#.#.#..
    0x00,  # ........
    0x54,  # .#.#.#..
    0x00,  # ........
    0x00,  # ........
)

HOUSING = (
    0x3C,  # ..####..   a ring with a lens: the searchlight, bolted down
    0x42,  # .#....#.
    0x81,  # #......#
    0x99,  # #..##..#
    0x99,  # #..##..#
    0x81,  # #......#
    0x42,  # .#....#.
    0x3C,  # ..####..
)

#: HOUSING's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
HOUSING_MASK = (
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

KEY = (
    0x00,  # ........
    0x1C,  # ...###..   ring
    0x22,  # ..#...#.
    0x22,  # ..#...#.
    0x1C,  # ...###..
    0x08,  # ....#...   shaft
    0x0E,  # ....###.   teeth
    0x00,  # ........
)

#: KEY's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
KEY_MASK = (
    0x3E,  # ..#####.
    0x7F,  # .#######
    0x7F,  # .#######
    0x7F,  # .#######
    0x7F,  # .#######
    0x3F,  # ..######
    0x1F,  # ...#####
    0x1F,  # ...#####
)

LAMP_OFF = (
    0x3C,  # ..####..   a hollow octagon: a spotlight lying dark
    0x42,  # .#....#.
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0x42,  # .#....#.
    0x3C,  # ..####..
)

#: LAMP_OFF's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
LAMP_OFF_MASK = (
    0xFF,  # ########
    0xFF,  # ########
    0xE7,  # ###..###
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xE7,  # ###..###
    0xFF,  # ########
    0xFF,  # ########
)

LAMP_ON = (
    0x3C,  # ..####..   filled: the same spotlight burning
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x7E,  # .######.
    0x3C,  # ..####..
)

#: LAMP_ON's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
LAMP_ON_MASK = (
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

NEST = (
    0x00,  # ........
    0x30,  # ..##....   the lip, broken and off-centre
    0x7C,  # .#####..
    0xFE,  # #######.
    0xDF,  # ##.#####   the brood, uneven
    0xFF,  # ########
    0x7E,  # .######.
    0x2C,  # ..#.##..   it does not sit square
)

#: NEST's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
NEST_MASK = (
    0x78,  # .####...
    0xFE,  # #######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

PIPE_H = (
    0x00,  # ........   a pipe run, east-west: two flanged joints and the barrel
    0xDB,  # ##.##.##
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0xDB,  # ##.##.##
    0x00,  # ........
)

PIPE_V = (
    0x3C,  # ..####..   a riser, north-south: the same pipe standing up
    0x42,  # .#....#.
    0x42,  # .#....#.
    0x42,  # .#....#.
    0xC3,  # ##....##   a flange
    0x42,  # .#....#.
    0x42,  # .#....#.
    0xC3,  # ##....##
)

PLAYER_A = (
    0x00,  # ........
    0x3C,  # ..####..   the lamp, worn on the helmet
    0x3C,  # ..####..
    0x7E,  # .######.   helmet, a disc four rows deep
    0x7E,  # .######.
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########   shoulders, full width - the kit
    0xFF,  # ########
    0xBC,  # #.####..   a hand forward, beside the hip
    0x19,  # ...##..#   the other hand, swung back
    0x0C,  # ....##..   a foot out from under
    0x30,  # ..##....   the other, behind
    0x00,  # ........   one clear row, so the mark is not feet
    0xFF,  # ########   the mark: the only figure with ground under him
    0xFF,  # ########
)

#: PLAYER_A's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
PLAYER_A_MASK = (
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x7F,  # .#######
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

PLAYER_B = (
    0x00,  # ........
    0x3C,  # ..####..   the lamp
    0x3C,  # ..####..
    0x7E,  # .######.   helmet
    0x7E,  # .######.
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########   shoulders
    0xFF,  # ########
    0x3D,  # ..####.#   frame A in the mirror: the other hand forward
    0x98,  # #..##...
    0x30,  # ..##....   feet swapped
    0x0C,  # ....##..
    0x00,  # ........
    0xFF,  # ########   the mark
    0xFF,  # ########
)

#: PLAYER_B's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
PLAYER_B_MASK = (
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFE,  # #######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

SPRAY = (
    0x00,  # ........   scattered droplets, staggered so they are not the floor's columns
    0x22,  # ..#...#.
    0x00,  # ........
    0x88,  # #...#...
    0x00,  # ........
    0x22,  # ..#...#.
    0x00,  # ........
    0x88,  # #...#...
)

WALL_DIM_00 = (
    0xFF,  # ########   mask  0, -
    0xFF,  # ########
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xEB,  # ###.#.##
    0xFF,  # ########
    0xFF,  # ########
)

WALL_DIM_01 = (
    0x81,  # #......#   mask  1, N
    0xAB,  # #.#.#.##
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xAB,  # #.#.#.##
    0xFF,  # ########
    0xFF,  # ########
)

WALL_DIM_02 = (
    0xFF,  # ########   mask  2, E
    0xEA,  # ###.#.#.
    0xC0,  # ##......
    0xC0,  # ##......
    0xC0,  # ##......
    0xEA,  # ###.#.#.
    0xC0,  # ##......
    0xFF,  # ########
)

WALL_DIM_03 = (
    0x80,  # #.......   mask  3, NE
    0xAA,  # #.#.#.#.
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0xAA,  # #.#.#.#.
    0x80,  # #.......
    0xFF,  # ########
)

WALL_DIM_04 = (
    0xFF,  # ########   mask  4, S
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xAB,  # #.#.#.##
    0x81,  # #......#
    0x81,  # #......#
)

WALL_DIM_05 = (
    0x81,  # #......#   mask  5, NS
    0xAB,  # #.#.#.##
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xAB,  # #.#.#.##
    0x81,  # #......#
    0x81,  # #......#
)

WALL_DIM_06 = (
    0xFF,  # ########   mask  6, ES
    0xAA,  # #.#.#.#.
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0xAA,  # #.#.#.#.
    0x80,  # #.......
    0x80,  # #.......
)

WALL_DIM_07 = (
    0x80,  # #.......   mask  7, NES
    0xAA,  # #.#.#.#.
    0x80,  # #.......
    0x80,  # #.......
    0x80,  # #.......
    0xAA,  # #.#.#.#.
    0x80,  # #.......
    0x80,  # #.......
)

WALL_DIM_08 = (
    0xFF,  # ########   mask  8, W
    0xAB,  # #.#.#.##
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0xAB,  # #.#.#.##
    0x03,  # ......##
    0xFF,  # ########
)

WALL_DIM_09 = (
    0x01,  # .......#   mask  9, NW
    0xAB,  # #.#.#.##
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xAB,  # #.#.#.##
    0x01,  # .......#
    0xFF,  # ########
)

WALL_DIM_10 = (
    0xFF,  # ########   mask 10, EW
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0xFF,  # ########
)

WALL_DIM_11 = (
    0x00,  # ........   mask 11, NEW
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0xFF,  # ########
)

WALL_DIM_12 = (
    0xFF,  # ########   mask 12, SW
    0xAB,  # #.#.#.##
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xAB,  # #.#.#.##
    0x01,  # .......#
    0x01,  # .......#
)

WALL_DIM_13 = (
    0x01,  # .......#   mask 13, NSW
    0xAB,  # #.#.#.##
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xAB,  # #.#.#.##
    0x01,  # .......#
    0x01,  # .......#
)

WALL_DIM_14 = (
    0xFF,  # ########   mask 14, ESW
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0x00,  # ........
)

WALL_DIM_15 = (
    0x00,  # ........   mask 15, NESW
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
    0xAA,  # #.#.#.#.
    0x00,  # ........
    0x00,  # ........
)

WALL_LIT_00 = (
    0xFF,  # ########   mask  0, -
    0xFF,  # ########
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

WALL_LIT_01 = (
    0x91,  # #..#...#   mask  1, N
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
)

WALL_LIT_02 = (
    0xFF,  # ########   mask  2, E
    0xFF,  # ########
    0xC1,  # ##.....#
    0xC1,  # ##.....#
    0xC1,  # ##.....#
    0xFF,  # ########
    0xD0,  # ##.#....
    0xFF,  # ########
)

WALL_LIT_03 = (
    0x90,  # #..#....   mask  3, NE
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x90,  # #..#....
    0xFF,  # ########
)

WALL_LIT_04 = (
    0xFF,  # ########   mask  4, S
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x91,  # #..#...#
    0x91,  # #..#...#
)

WALL_LIT_05 = (
    0x91,  # #..#...#   mask  5, NS
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x91,  # #..#...#
    0x91,  # #..#...#
)

WALL_LIT_06 = (
    0xFF,  # ########   mask  6, ES
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x90,  # #..#....
    0x90,  # #..#....
)

WALL_LIT_07 = (
    0x90,  # #..#....   mask  7, NES
    0xFF,  # ########
    0x81,  # #......#
    0x81,  # #......#
    0x81,  # #......#
    0xFF,  # ########
    0x90,  # #..#....
    0x90,  # #..#....
)

WALL_LIT_08 = (
    0xFF,  # ########   mask  8, W
    0xFF,  # ########
    0x03,  # ......##
    0x03,  # ......##
    0x03,  # ......##
    0xFF,  # ########
    0x13,  # ...#..##
    0xFF,  # ########
)

WALL_LIT_09 = (
    0x11,  # ...#...#   mask  9, NW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x11,  # ...#...#
    0xFF,  # ########
)

WALL_LIT_10 = (
    0xFF,  # ########   mask 10, EW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0xFF,  # ########
)

WALL_LIT_11 = (
    0x10,  # ...#....   mask 11, NEW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0xFF,  # ########
)

WALL_LIT_12 = (
    0xFF,  # ########   mask 12, SW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x11,  # ...#...#
    0x11,  # ...#...#
)

WALL_LIT_13 = (
    0x11,  # ...#...#   mask 13, NSW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x11,  # ...#...#
    0x11,  # ...#...#
)

WALL_LIT_14 = (
    0xFF,  # ########   mask 14, ESW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0x10,  # ...#....
)

WALL_LIT_15 = (
    0x10,  # ...#....   mask 15, NESW
    0xFF,  # ########
    0x01,  # .......#
    0x01,  # .......#
    0x01,  # .......#
    0xFF,  # ########
    0x10,  # ...#....
    0x10,  # ...#....
)

WORKER_A = (
    0x00,  # ........
    0xC3,  # ##....##   hands, raised beside the crown
    0xC3,  # ##....##
    0x18,  # ...##...   head, a row lower than the follower's
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x7E,  # .######.   shoulders
    0x7E,  # .######.
    0x18,  # ...##...   hips - the arms are up, so no hands here
    0x18,  # ...##...
    0x0C,  # ....##..   feet
    0x30,  # ..##....
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

#: WORKER_A's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
WORKER_A_MASK = (
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xFF,  # ########
    0xFF,  # ########
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x3E,  # ..#####.
    0x7E,  # .######.
    0x7E,  # .######.
    0x78,  # .####...
    0x00,  # ........
    0x00,  # ........
)

WORKER_B = (
    0x00,  # ........
    0xC3,  # ##....##   hands, raised
    0xC3,  # ##....##
    0x18,  # ...##...   head
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x7E,  # .######.   shoulders
    0x7E,  # .######.
    0x18,  # ...##...   hips
    0x18,  # ...##...
    0x30,  # ..##....   feet swapped
    0x0C,  # ....##..
    0x00,  # ........
    0x00,  # ........
    0x00,  # ........
)

#: WORKER_B's mask: the ink dilated one pixel, clipped to its box.
#: Derived by tools/bitmaps.py; a set bit is a pixel to clear.
WORKER_B_MASK = (
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xFF,  # ########
    0xFF,  # ########
    0x7E,  # .######.
    0x7E,  # .######.
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0xFF,  # ########
    0x7C,  # .#####..
    0x7E,  # .######.
    0x7E,  # .######.
    0x1E,  # ...####.
    0x00,  # ........
    0x00,  # ........
)

#: Every bitmap by name, for the tools and tests that want to
#: walk them all.
BITMAPS = {
    "BATTEN": BATTEN,
    "BODY": BODY,
    "CABINET": CABINET,
    "CLEG_A": CLEG_A,
    "CLEG_B": CLEG_B,
    "CLEG_M": CLEG_M,
    "CRATE": CRATE,
    "DESK_L": DESK_L,
    "DESK_R": DESK_R,
    "DOORWAY_00": DOORWAY_00,
    "DOORWAY_01": DOORWAY_01,
    "DOORWAY_02": DOORWAY_02,
    "DOORWAY_03": DOORWAY_03,
    "DOORWAY_04": DOORWAY_04,
    "DOORWAY_05": DOORWAY_05,
    "DOORWAY_06": DOORWAY_06,
    "DOORWAY_07": DOORWAY_07,
    "DOORWAY_08": DOORWAY_08,
    "DOORWAY_09": DOORWAY_09,
    "DOORWAY_10": DOORWAY_10,
    "DOORWAY_11": DOORWAY_11,
    "DOORWAY_12": DOORWAY_12,
    "DOORWAY_13": DOORWAY_13,
    "DOORWAY_14": DOORWAY_14,
    "DOORWAY_15": DOORWAY_15,
    "DOOR_LOCKED": DOOR_LOCKED,
    "DOOR_OPEN": DOOR_OPEN,
    "FLOOR_DIM_00": FLOOR_DIM_00,
    "FLOOR_DIM_01": FLOOR_DIM_01,
    "FLOOR_DIM_02": FLOOR_DIM_02,
    "FLOOR_DIM_03": FLOOR_DIM_03,
    "FLOOR_DIM_04": FLOOR_DIM_04,
    "FLOOR_DIM_05": FLOOR_DIM_05,
    "FLOOR_DIM_06": FLOOR_DIM_06,
    "FLOOR_DIM_07": FLOOR_DIM_07,
    "FLOOR_DIM_08": FLOOR_DIM_08,
    "FLOOR_DIM_09": FLOOR_DIM_09,
    "FLOOR_DIM_10": FLOOR_DIM_10,
    "FLOOR_DIM_11": FLOOR_DIM_11,
    "FLOOR_DIM_12": FLOOR_DIM_12,
    "FLOOR_DIM_13": FLOOR_DIM_13,
    "FLOOR_DIM_14": FLOOR_DIM_14,
    "FLOOR_DIM_15": FLOOR_DIM_15,
    "FLOOR_LIT_00": FLOOR_LIT_00,
    "FLOOR_LIT_01": FLOOR_LIT_01,
    "FLOOR_LIT_02": FLOOR_LIT_02,
    "FLOOR_LIT_03": FLOOR_LIT_03,
    "FLOOR_LIT_04": FLOOR_LIT_04,
    "FLOOR_LIT_05": FLOOR_LIT_05,
    "FLOOR_LIT_06": FLOOR_LIT_06,
    "FLOOR_LIT_07": FLOOR_LIT_07,
    "FLOOR_LIT_08": FLOOR_LIT_08,
    "FLOOR_LIT_09": FLOOR_LIT_09,
    "FLOOR_LIT_10": FLOOR_LIT_10,
    "FLOOR_LIT_11": FLOOR_LIT_11,
    "FLOOR_LIT_12": FLOOR_LIT_12,
    "FLOOR_LIT_13": FLOOR_LIT_13,
    "FLOOR_LIT_14": FLOOR_LIT_14,
    "FLOOR_LIT_15": FLOOR_LIT_15,
    "FOLLOWER_A": FOLLOWER_A,
    "FOLLOWER_B": FOLLOWER_B,
    "GRATING": GRATING,
    "HOUSING": HOUSING,
    "KEY": KEY,
    "LAMP_OFF": LAMP_OFF,
    "LAMP_ON": LAMP_ON,
    "NEST": NEST,
    "PIPE_H": PIPE_H,
    "PIPE_V": PIPE_V,
    "PLAYER_A": PLAYER_A,
    "PLAYER_B": PLAYER_B,
    "SPRAY": SPRAY,
    "WALL_DIM_00": WALL_DIM_00,
    "WALL_DIM_01": WALL_DIM_01,
    "WALL_DIM_02": WALL_DIM_02,
    "WALL_DIM_03": WALL_DIM_03,
    "WALL_DIM_04": WALL_DIM_04,
    "WALL_DIM_05": WALL_DIM_05,
    "WALL_DIM_06": WALL_DIM_06,
    "WALL_DIM_07": WALL_DIM_07,
    "WALL_DIM_08": WALL_DIM_08,
    "WALL_DIM_09": WALL_DIM_09,
    "WALL_DIM_10": WALL_DIM_10,
    "WALL_DIM_11": WALL_DIM_11,
    "WALL_DIM_12": WALL_DIM_12,
    "WALL_DIM_13": WALL_DIM_13,
    "WALL_DIM_14": WALL_DIM_14,
    "WALL_DIM_15": WALL_DIM_15,
    "WALL_LIT_00": WALL_LIT_00,
    "WALL_LIT_01": WALL_LIT_01,
    "WALL_LIT_02": WALL_LIT_02,
    "WALL_LIT_03": WALL_LIT_03,
    "WALL_LIT_04": WALL_LIT_04,
    "WALL_LIT_05": WALL_LIT_05,
    "WALL_LIT_06": WALL_LIT_06,
    "WALL_LIT_07": WALL_LIT_07,
    "WALL_LIT_08": WALL_LIT_08,
    "WALL_LIT_09": WALL_LIT_09,
    "WALL_LIT_10": WALL_LIT_10,
    "WALL_LIT_11": WALL_LIT_11,
    "WALL_LIT_12": WALL_LIT_12,
    "WALL_LIT_13": WALL_LIT_13,
    "WALL_LIT_14": WALL_LIT_14,
    "WALL_LIT_15": WALL_LIT_15,
    "WORKER_A": WORKER_A,
    "WORKER_B": WORKER_B,
}

#: Every sprite's mask, keyed by the sprite's name (issue #70).
#: Tiles are not in it: they composite by OR and have none.
MASKS = {
    "BATTEN": BATTEN_MASK,
    "BODY": BODY_MASK,
    "CLEG_A": CLEG_A_MASK,
    "CLEG_B": CLEG_B_MASK,
    "CLEG_M": CLEG_M_MASK,
    "DOOR_LOCKED": DOOR_LOCKED_MASK,
    "DOOR_OPEN": DOOR_OPEN_MASK,
    "FOLLOWER_A": FOLLOWER_A_MASK,
    "FOLLOWER_B": FOLLOWER_B_MASK,
    "HOUSING": HOUSING_MASK,
    "KEY": KEY_MASK,
    "LAMP_OFF": LAMP_OFF_MASK,
    "LAMP_ON": LAMP_ON_MASK,
    "NEST": NEST_MASK,
    "PLAYER_A": PLAYER_A_MASK,
    "PLAYER_B": PLAYER_B_MASK,
    "WORKER_A": WORKER_A_MASK,
    "WORKER_B": WORKER_B_MASK,
}
