"""Bitmaps, generated by tools/bitmaps.py. Do not edit.

Source: assets/logo. Regenerate with::

    python tools/bitmaps.py --python <this file> assets/logo

Bit 7 is the leftmost pixel, one byte per row, rows top to bottom --
the Spectrum's own order, which is what `core.Screen` models.

There is no timestamp here on purpose: this file is committed, and a
test regenerates it and compares byte for byte, so any diff at all is
art and code having drifted.
"""

LOGO_G = (
    0x3C,  # ..####..
    0x7E,  # .######.
    0xE7,  # ###..###
    0xC3,  # ##....##
    0xC0,  # ##......
    0xC0,  # ##......
    0xC0,  # ##......
    0xCF,  # ##..####   the spur, which is the whole difference from O
    0xCF,  # ##..####
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xE7,  # ###..###
    0x7E,  # .######.
    0x3C,  # ..####..
    0x00,  # ........
)

LOGO_H = (
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xFF,  # ########   the crossbar, on the seam between the two cell rows
    0xFF,  # ########
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0x00,  # ........
)

LOGO_I = (
    0xFF,  # ########   serifed top and bottom, or it would read as the stem of a T
    0xFF,  # ########
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0xFF,  # ########
    0xFF,  # ########
    0x00,  # ........
)

LOGO_L = (
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xFF,  # ########   the foot, and it reaches the full width like T's arm
    0xFF,  # ########
    0x00,  # ........
)

LOGO_O = (
    0x3C,  # ..####..
    0x7E,  # .######.
    0xE7,  # ###..###
    0xC3,  # ##....##   two-pixel sides, so the counter stays open at 1:1
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xC3,  # ##....##
    0xE7,  # ###..###
    0x7E,  # .######.
    0x3C,  # ..####..
    0x00,  # ........
)

LOGO_P = (
    0xFC,  # ######..
    0xFE,  # #######.
    0xE7,  # ###..###
    0xE3,  # ###...##
    0xE3,  # ###...##
    0xE7,  # ###..###
    0xFE,  # #######.
    0xFC,  # ######..   the bowl closes here
    0xE0,  # ###.....   and the stem runs the rest of the way down
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xE0,  # ###.....
    0x00,  # ........
)

LOGO_S = (
    0x3C,  # ..####..   the top curve, three pixels thick
    0x7E,  # .######.
    0xE7,  # ###..###
    0xE0,  # ###.....
    0xE0,  # ###.....
    0xF0,  # ####....   the waist turns back on itself
    0x7C,  # .#####..
    0x3E,  # ..#####.
    0x07,  # .....###   and comes down the other side
    0x03,  # ......##
    0x03,  # ......##
    0xE7,  # ###..###
    0xE7,  # ###..###
    0x7E,  # .######.
    0x3C,  # ..####..
    0x00,  # ........   the baseline row every glyph ends on
)

LOGO_T = (
    0xFF,  # ########   a full-width arm -- the spacing is the blank cell either side
    0xFF,  # ########
    0x3C,  # ..####..   a four-pixel stem, centred
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x3C,  # ..####..
    0x00,  # ........
)

#: Every bitmap by name, for the tools and tests that want to
#: walk them all.
BITMAPS = {
    "LOGO_G": LOGO_G,
    "LOGO_H": LOGO_H,
    "LOGO_I": LOGO_I,
    "LOGO_L": LOGO_L,
    "LOGO_O": LOGO_O,
    "LOGO_P": LOGO_P,
    "LOGO_S": LOGO_S,
    "LOGO_T": LOGO_T,
}
