"""Furniture: seven tiles a room can be authored with (issue #74).

From *A place, not a diagram* in the vault. **What was wrong before**: the
building was a diagram. Rule 5 of *Art Direction* -- anything drawn is a claim
that it matters -- had been read as *nothing is drawn that is not a mechanic*,
so a building where seven people are bleeding to death had no desk in it. The
fix is seven tiles with a legend character each: six that are walls for every
mechanical purpose and draw their own tile instead of the masonry, and one
that is floor and draws its own tile instead of the stipple. The dim variant
of each is generated by rule, never drawn.

The tests here pin four things separately, because they can fail separately:

* **the legend** -- a solid kind is solid and is wall to its neighbours' masks
  everywhere the game asks, the grating is not, and the surge's plan agrees;
* **the art** -- the seven lit tiles came through the pipeline, the dim tiles
  are the rule applied to them and nothing else, and none of them is an
  octagon, because the lamp family's silhouette is reserved;
* **the drawing** -- a solid piece draws its own tile instead of the wall's
  and never the masonry under it, a grating draws instead of the stipple, a
  dark cell draws nothing, and paint hides texture here as it does on walls;
* **the geometry** -- each room's solidity bitmap is held against a stored
  copy, so that a piece of furniture authored onto floor, which would move
  collision, the swarm's reach and the event log, has to change this file on
  purpose. That last pin is what makes the slice log-identical by
  construction rather than by luck.
"""

import pathlib

import pytest

from spikes import building, floor, lighting as L, scene, surge, tiles
from spikes import spike_gallery as gallery
from spikes.bitmaps_gen import BITMAPS
from spikes.layout import PLAY_ROWS
from spotlight.core.constants import CELL, COLS, SCREEN_W, WHITE
from spotlight.core.screen import Screen

ROOT = pathlib.Path(__file__).resolve().parents[2]
ASSET = ROOT / "assets" / "tiles" / "furniture.txt"

#: The seven, and the tile each wears, as the issue lists them.
KINDS = {
    building.PIPE_H: "PIPE_H",
    building.PIPE_V: "PIPE_V",
    building.CRATE: "CRATE",
    building.DESK_L: "DESK_L",
    building.DESK_R: "DESK_R",
    building.CABINET: "CABINET",
    building.GRATING: "GRATING",
}

#: **The stored copy of each room's solidity**, one character per cell, `#`
#: where nothing can stand. This is the geometry the difficulty targets and
#: the byte-identical event log were taken against. A solid piece of
#: furniture may only replace a `#` here and a grating only a `.`; a level
#: change that moves a `#` must change this table on purpose, with the
#: targets re-taken, because it moves collision, steering and the swarm's
#: reach. See *Building Structure* in the vault.
STORED_SOLIDITY = {
    scene.NEAR_NAME: (
        "################################",
        "#......#.......................#",
        "#......#.......................#",
        "#......#....########...........#",
        "#......#....#......#...........#",
        "#......#....#......#...........#",
        "#...........#......#...........#",
        "#...........###.####...........#",
        "#..............................#",
        "#####.#####....................#",
        "................................",
        "..........#####.................",
        "#...............................",
        "#..............................#",
        "#..............................#",
        "#..........########............#",
        "#..............................#",
        "#.......................#......#",
        "#.......................#......#",
        "#.......................#......#",
        "#.......................#......#",
        "################################",
    ),
    scene.FAR_NAME: (
        "################################",
        "#..............................#",
        "#..............................#",
        "#....#........#........#.......#",
        "#....#........#........#.......#",
        "#....#........#........#.......#",
        "#....#........#........#.......#",
        "#..............................#",
        "#..............................#",
        "#........####........####......#",
        ".........####........####......#",
        "...............................#",
        ".........####........####......#",
        "#........####........####......#",
        "#..............................#",
        "#..............................#",
        "#.......#........#........#....#",
        "#.......#........#........#....#",
        "#.......#........#........#....#",
        "#.......#........#........#....#",
        "#..............................#",
        "################################",
    ),
}


def _solidity(room) -> tuple:
    """A room's solidity bitmap as the stored copy is written."""
    bits = room.solid_map()
    return tuple("".join("#" if bits[cy * COLS + cx] else "."
                         for cx in range(COLS))
                 for cy in range(PLAY_ROWS))


def _blank_room(**cells) -> building.Room:
    """A scratch room: a `#` border, floor inside, and `cells` placed in it,
    given as `{(cx, cy): char}` via the single keyword `at`."""
    at = cells.get("at", {})
    rows = []
    for cy in range(PLAY_ROWS):
        row = []
        for cx in range(COLS):
            edge = cx in (0, COLS - 1) or cy in (0, PLAY_ROWS - 1)
            row.append(at.get((cx, cy), "#" if edge else "."))
        rows.append("".join(row))
    return building.Room("scratch", rows)


def _field(*cells) -> L.LightField:
    """A light field with the given `(cx, cy, level)` cells set."""
    f = L.LightField()
    f.begin()
    for cx, cy, level in cells:
        f.add(cx, cy, level, L.CHARGE_LIT if level == L.LIT else L.CHARGE_DIM)
    f.commit()
    return f


def _cell(screen, cx, cy) -> tuple:
    """A cell's eight rows, as the bytes a tile would have set."""
    out = []
    for dy in range(CELL):
        bits = 0
        for dx in range(CELL):
            if screen.pixels[(cy * CELL + dy) * SCREEN_W + cx * CELL + dx]:
                bits |= 0x80 >> dx
        out.append(bits)
    return tuple(out)


# --- the legend -------------------------------------------------------------

def test_the_legend_has_seven_furniture_characters_and_no_two_alike():
    """The count is the rule; the glyphs are a choice. Seven kinds, six of
    them solid, none of them a character the legend already had."""
    assert len(building.FURNITURE) == 7
    assert len(set(building.FURNITURE)) == 7
    assert building.SOLID_FURNITURE == building.FURNITURE[:6]
    assert building.GRATING == building.FURNITURE[6]
    old = {building.WALL, building.FLOOR, building.DOOR, building.KEY,
           building.DOORWAY}
    assert not old & set(building.FURNITURE)
    assert set(building.CELL_KINDS) == old | set(building.FURNITURE)


@pytest.mark.parametrize("kind", building.SOLID_FURNITURE)
def test_each_solid_kind_is_solid_and_is_wall_everywhere_it_is_asked(kind):
    """`is_solid` is the authority on what is walkable and `is_wall` on what
    the tile mask sees, and a solid piece answers as `#` to both. There is
    no third list to keep in step: both read `building.SOLID`."""
    assert kind in building.SOLID
    room = _blank_room(at={(10, 10): kind})
    assert room.is_solid(10, 10)
    assert room.is_wall(10, 10)
    assert room.furniture_at(10, 10) == kind


@pytest.mark.parametrize("kind", building.SOLID_FURNITURE)
def test_a_solid_piece_is_wall_to_its_neighbours_masks(kind):
    """The cell east of a crate has WEST set, and so on round it -- which is
    what makes a wall run end against a pipe the way it ends against
    masonry, and what the floor pass needs so it does not stipple a desk."""
    room = _blank_room(at={(10, 10): kind})
    assert tiles.mask_at(room.is_wall, 11, 10) & tiles.WEST
    assert tiles.mask_at(room.is_wall, 9, 10) & tiles.EAST
    assert tiles.mask_at(room.is_wall, 10, 11) & tiles.NORTH
    assert tiles.mask_at(room.is_wall, 10, 9) & tiles.SOUTH
    # And the piece itself, boxed in by walls, would see all four -- not that
    # its own tile is chosen by a mask, see the drawing tests.
    boxed = _blank_room(at={(10, 10): kind, (9, 10): "#", (11, 10): "#",
                            (10, 9): "#", (10, 11): "#"})
    assert tiles.mask_at(boxed.is_wall, 10, 10) == 15


def test_the_grating_is_floor_everywhere_it_is_asked():
    """Walkable, not wall to a neighbour's mask, and floor to the swarm: a
    grille in the floor is somewhere a fly can stand."""
    from spikes import swarming
    assert building.GRATING not in building.SOLID
    room = _blank_room(at={(10, 10): building.GRATING})
    assert not room.is_solid(10, 10)
    assert not room.is_wall(10, 10)
    assert room.furniture_at(10, 10) == building.GRATING
    assert tiles.mask_at(room.is_wall, 11, 10) == 0
    # The swarm starts from where the flies are, never from a grid over the
    # floor, so the scratch room needs a fly in it to have anywhere reached.
    swarmed = building.Room("scratch", room.rows, clegs=[(5, 5)])
    assert (10, 10) not in swarming.unswarmable(swarmed)


def test_a_wall_and_a_floor_cell_are_not_furniture():
    room = _blank_room()
    assert room.furniture_at(0, 0) is None
    assert room.furniture_at(10, 10) is None
    assert room.furniture_at(-1, 10) is None and room.furniture_at(COLS, 10) is None


def test_solid_furniture_is_white_and_the_grating_takes_the_floors_hue():
    """WHITE means solid in every room of every building; a crate the colour
    of the floor would be a wall you could not tell from the ground. The
    grating is floor and follows the room, as the floor does."""
    from spotlight.core.constants import CYAN
    ink = building.palette(CYAN)
    for kind in building.SOLID_FURNITURE:
        assert ink[kind] == WHITE
        assert building.CONSTANT_INK[kind] == WHITE
    assert ink[building.GRATING] == CYAN
    assert building.GRATING not in building.CONSTANT_INK
    room = building.Room("scratch", _blank_room().rows, ink=ink)
    room.validate()


def test_a_room_with_every_kind_in_it_validates():
    """The legend is the format: a room written with all seven is a room."""
    at = {(10 + i, 10): kind for i, kind in enumerate(building.FURNITURE)}
    room = building.Room("scratch", _blank_room(at=at).rows,
                         ink=building.palette(WHITE))
    room.validate()


def test_the_surge_plan_draws_solid_furniture_as_wall():
    """The plan says where you cannot walk, and a crate is somewhere you
    cannot walk. Counted through `surge.draw`'s own drawing: a room whose
    only interior solid cell is a crate lights one more plan cell than the
    same room with floor there, and a grating lights none."""
    def solid_plan_cells(room):
        screen = Screen()
        surge.draw(screen, [room], [])
        return sum(1 for p in screen.pixels if p)

    empty = _blank_room()
    crate = _blank_room(at={(10, 10): building.CRATE})
    wall = _blank_room(at={(10, 10): building.WALL})
    grating = _blank_room(at={(10, 10): building.GRATING})
    assert solid_plan_cells(crate) == solid_plan_cells(wall) \
        > solid_plan_cells(empty) == solid_plan_cells(grating)


# --- the art ----------------------------------------------------------------

def test_the_seven_tiles_came_out_of_the_pipeline():
    """Authored in `assets/tiles/furniture.txt`, generated by
    `tools/bitmaps.py`, read from the generated table and nowhere else."""
    assert ASSET.exists()
    text = ASSET.read_text()
    for kind, name in KINDS.items():
        assert f"name: {name}\nsize: 8x8\n" in text, name
        assert tiles.FURNITURE[kind] is BITMAPS[name]
        assert len(tiles.FURNITURE[kind]) == 8
    assert set(tiles.FURNITURE) == set(building.FURNITURE)


def test_the_tiles_are_the_ones_the_issue_drew():
    """The bytes, so that a redraw is a decision and not a slip."""
    assert tiles.FURNITURE[building.PIPE_H] == (
        0x00, 0xDB, 0xFF, 0x81, 0x81, 0xFF, 0xDB, 0x00)
    assert tiles.FURNITURE[building.PIPE_V] == (
        0x3C, 0x42, 0x42, 0x42, 0xC3, 0x42, 0x42, 0xC3)
    assert tiles.FURNITURE[building.CRATE] == (
        0xFF, 0x81, 0xA5, 0x99, 0x99, 0xA5, 0x81, 0xFF)
    # Row 3 is 0x2A and not 0x54 since issue #77, so that the dim rule drops
    # it: see `test_the_grating_thins_when_remembered_like_everything_else`.
    assert tiles.FURNITURE[building.GRATING] == (
        0x00, 0x54, 0x00, 0x2A, 0x00, 0x54, 0x00, 0x00)
    assert tiles.FURNITURE[building.DESK_L] == (
        0xFF, 0x81, 0xBD, 0xA5, 0xBD, 0x81, 0xFF, 0x00)
    assert tiles.FURNITURE[building.DESK_R] == (
        0xFF, 0x81, 0x81, 0x81, 0x81, 0x81, 0xFF, 0x00)
    assert tiles.FURNITURE[building.CABINET] == (
        0xFF, 0x81, 0xBD, 0x81, 0xBD, 0x81, 0xBD, 0xFF)


@pytest.mark.parametrize("kind", building.FURNITURE)
def test_each_dim_tile_is_the_rule_applied_to_its_lit_tile(kind):
    """Row `y` of the lit tile ANDed with 0xAA when `y` is even and 0x55 when
    odd -- every other pixel, phase alternating by row. Written out here
    rather than through `tiles.dim_of`, so that the rule is pinned and not
    merely whatever the function does; and then through it, so the table is
    the function's output and not a hand-drawn second set."""
    lit = tiles.FURNITURE[kind]
    want = tuple(bits & (0xAA if y % 2 == 0 else 0x55)
                 for y, bits in enumerate(lit))
    assert tiles.FURNITURE_DIM[kind] == want
    assert tiles.dim_of(lit) == want
    # A ghost and not a second drawing: nothing set that the lit tile has not.
    assert all(d & ~l == 0 for d, l in zip(want, lit))
    # A checker, not stripes: every dim row keeps only pixels of one parity,
    # and adjacent rows keep opposite parities.
    for y, bits in enumerate(want):
        keep = 0xAA if y % 2 == 0 else 0x55
        assert bits & ~keep == 0


def test_the_dim_tiles_are_not_in_the_generated_table():
    """Generated at load and not by the converter, so the port's ROM figure
    is the 56 lit bytes: the asset holds seven blocks and the table holds no
    `*_DIM` for any of them."""
    for name in KINDS.values():
        assert f"{name}_DIM" not in BITMAPS
    furniture_blocks = [n for n in BITMAPS if n in KINDS.values()]
    assert len(furniture_blocks) == 7


def test_the_dim_rule_loses_about_half_of_every_solid_tile():
    """The point of the rule is a ghost, and a ghost is thinner. Nothing has
    to be exactly half -- an outline row of 0xFF loses four of eight, a row of
    0x81 may keep both or neither -- but no solid tile keeps more than it
    loses. The grating keeps six of nine, and has its own test below, because
    a grille of dots is already sparse and a third of it is all the rule can
    take without taking the lot."""
    for kind in building.SOLID_FURNITURE:
        lit = tiles.ink_of(tiles.FURNITURE[kind])
        dim = tiles.ink_of(tiles.FURNITURE_DIM[kind])
        assert 0 < dim <= lit // 2 + 1, (kind, lit, dim)


def test_the_grating_thins_when_remembered_like_everything_else():
    """**The exception that became the ordinary case** (issue #77). As #74
    drew it the grating was three rows of `.#.#.#..` on rows 1, 3 and 5 --
    every dot on an odd pixel of an odd row, the half the rule keeps -- so
    `dim_of(GRATING) == GRATING` and a remembered grating showed nine dots
    beside floor that remembers one: the one tile that handed over more when
    remembered than when seen, the opposite of what the fade says. The
    ruling was that the art gives, not the rule: row 3 is `..#.#.#.` now,
    and the rule drops it.

    So the grating is pinned exactly as the other six are -- the dim tile is
    the rule applied to the lit one and a strict subset of it -- and with
    the numbers the ruling named: nine lit, six remembered. The last two
    assertions pin the thing that was wrong, on the two drawings that were
    considered and refused: a grille all on one pixel parity survives the
    rule whole (the #74 tile) or not at all (the same dots on even pixels),
    which is why a shift of one row and not of all three.
    """
    lit = tiles.FURNITURE[building.GRATING]
    dim = tiles.FURNITURE_DIM[building.GRATING]
    assert tiles.ink_of(lit) == 9
    assert tiles.ink_of(dim) == 6
    assert dim == tiles.dim_of(lit)
    assert dim != lit
    assert all(d & ~l == 0 for d, l in zip(dim, lit)), "dim is a subset of lit"
    # Rows 1 and 5 survive whole; row 3, the staggered one, goes.
    assert [y for y, bits in enumerate(lit) if bits] == [1, 3, 5]
    assert [y for y, bits in enumerate(dim) if bits] == [1, 5]
    assert lit[3] == 0x2A and dim[3] == 0x00
    assert dim[1] == lit[1] and dim[5] == lit[5]
    # The two refused drawings, so the reason for the stagger stays checkable.
    as_first_drawn = (0x00, 0x54, 0x00, 0x54, 0x00, 0x54, 0x00, 0x00)
    assert tiles.dim_of(as_first_drawn) == as_first_drawn
    all_even_pixels = (0x00, 0xA8, 0x00, 0xA8, 0x00, 0xA8, 0x00, 0x00)
    assert tiles.ink_of(tiles.dim_of(all_even_pixels)) == 0


#: The lamp's outline: an octagon, and the lamp family's alone. LAMP_OFF is
#: the hollow one, LAMP_ON fills it, and the housing is the same shape.
LAMP_OUTLINE = BITMAPS["LAMP_OFF"]


def test_no_furniture_tile_has_the_lamps_outline_rows():
    """A spotlight lying on the floor is the one object a player has to pick
    out of a room at a glance, so nothing else in a room may be round. The
    vault drew a drum and threw it away for this reason. Pinned as *no tile
    has the lamp's outline rows*: not its top-and-bottom chamfer pair, and
    not its rows at all."""
    chamfer = (LAMP_OUTLINE[0], LAMP_OUTLINE[7])
    assert chamfer == (0x3C, 0x3C), "the lamp is no longer an octagon?"
    for kind in building.FURNITURE:
        for table in (tiles.FURNITURE, tiles.FURNITURE_DIM):
            rows = table[kind]
            assert rows != LAMP_OUTLINE
            assert (rows[0], rows[7]) != chamfer, \
                f"{KINDS[kind]} is chamfered top and bottom like a lamp"
            # Nor the octagon's middle: the four 0x81 rows between the
            # chamfers, which is what makes a hollow octagon read as one.
            assert rows[1:7] != LAMP_OUTLINE[1:7], KINDS[kind]


def test_the_asset_says_why_the_dim_tiles_are_not_in_it():
    """The file is the source, so the rule that governs what is *not* in it
    has to be written there, where the next author will look."""
    text = ASSET.read_text()
    assert "dim" in text.lower() and "rule" in text.lower()
    assert "$AA" in text and "$55" in text


# --- the drawing ------------------------------------------------------------

@pytest.mark.parametrize("kind", building.SOLID_FURNITURE)
def test_a_lit_solid_piece_draws_its_own_tile_and_never_the_masonry(kind):
    """Exactly the tile: not the wall's tile, and not the wall's tile with
    the piece ORed over it. Boxed in on all four sides so that the wall tile
    it would otherwise wear -- mask 15, the masonry interior -- has pixels the
    piece does not, and the difference can be seen."""
    room = _blank_room(at={(10, 10): kind, (9, 10): "#", (11, 10): "#",
                           (10, 9): "#", (10, 11): "#"})
    screen = Screen()
    tiles.draw(screen, room, _field((10, 10, L.LIT)))
    assert _cell(screen, 10, 10) == tiles.FURNITURE[kind]
    assert _cell(screen, 10, 10) != tiles.WALL_LIT[15]


@pytest.mark.parametrize("kind", building.SOLID_FURNITURE)
def test_a_remembered_solid_piece_draws_its_dim_tile(kind):
    room = _blank_room(at={(10, 10): kind})
    screen = Screen()
    tiles.draw(screen, room, _field((10, 10, L.DIM)))
    assert _cell(screen, 10, 10) == tiles.FURNITURE_DIM[kind]
    assert _cell(screen, 10, 10) != tiles.WALL_DIM[0]


@pytest.mark.parametrize("kind", building.FURNITURE)
def test_a_dark_piece_of_furniture_draws_nothing(kind):
    """Black ink on black paper: the same picture for less work, and the
    picture the port draws."""
    room = _blank_room(at={(10, 10): kind})
    screen = Screen()
    tiles.draw(screen, room, _field())
    floor.draw(screen, _field(), room.is_solid, gratings={(10, 10)})
    assert _cell(screen, 10, 10) == (0,) * 8


def test_a_painted_solid_piece_draws_its_dim_tile_whatever_its_level():
    """The rule for walls -- paint hides texture and never shape -- is the
    rule for a crate with a word on it."""
    room = _blank_room(at={(10, 10): building.CRATE})
    screen = Screen()
    tiles.draw(screen, room, _field((10, 10, L.LIT)), painted={(10, 10)})
    assert _cell(screen, 10, 10) == tiles.FURNITURE_DIM[building.CRATE]


def test_the_wall_beside_a_piece_of_furniture_ends_against_it():
    """The neighbours' masks are the whole reason a solid piece is in
    `SOLID` and not merely drawn: the wall cell west of a pipe run sees a
    wall to its east, so it draws no east face and the run reads as one
    thing. Compared against the same cell beside floor."""
    with_pipe = _blank_room(at={(1, 10): building.PIPE_H})
    without = _blank_room()
    field = _field((0, 10, L.LIT))
    a, b = Screen(), Screen()
    tiles.draw(a, with_pipe, field)
    tiles.draw(b, without, field)
    assert tiles.mask_at(with_pipe.is_wall, 0, 10) & tiles.EAST
    assert not tiles.mask_at(without.is_wall, 0, 10) & tiles.EAST
    assert _cell(a, 0, 10) == tiles.WALL_LIT[tiles.mask_at(with_pipe.is_wall, 0, 10)]
    assert _cell(a, 0, 10) != _cell(b, 0, 10)


def test_a_solid_piece_is_not_stippled():
    """`floor.draw` asks `is_solid`, and a crate is solid, so the floor pass
    leaves it alone as it leaves a wall alone."""
    room = _blank_room(at={(10, 10): building.CRATE})
    screen = Screen()
    floor.draw(screen, _field((10, 10, L.LIT)), room.is_solid)
    assert _cell(screen, 10, 10) == (0,) * 8


def test_a_lit_grating_draws_its_tile_instead_of_the_stipple():
    """Instead of, not as well as: the cell is exactly the grille."""
    room = _blank_room(at={(10, 10): building.GRATING})
    screen = Screen()
    floor.draw(screen, _field((10, 10, L.LIT), (11, 10, L.LIT)),
               room.is_solid, gratings=frozenset(room.cells_of(building.GRATING)))
    assert _cell(screen, 10, 10) == tiles.FURNITURE[building.GRATING]
    assert _cell(screen, 11, 10) == floor.tile_at(L.LIT, 11, 10), \
        "the cell beside it is still stipple"


def test_a_remembered_grating_draws_its_dim_tile():
    room = _blank_room(at={(10, 10): building.GRATING})
    screen = Screen()
    floor.draw(screen, _field((10, 10, L.DIM)), room.is_solid,
               gratings={(10, 10)})
    assert _cell(screen, 10, 10) == tiles.FURNITURE_DIM[building.GRATING]


def test_a_painted_grating_draws_nothing_like_painted_floor():
    room = _blank_room(at={(10, 10): building.GRATING})
    screen = Screen()
    floor.draw(screen, _field((10, 10, L.LIT)), room.is_solid,
               painted={(10, 10)}, gratings={(10, 10)})
    assert _cell(screen, 10, 10) == (0,) * 8


def test_the_wall_pass_never_draws_a_grating():
    """A grating is floor and floor is `floor.draw`'s. If the wall pass drew
    it too, the tile would be ORed twice -- harmless today, and a second
    drawing of a floor cell on the port."""
    room = _blank_room(at={(10, 10): building.GRATING})
    screen = Screen()
    tiles.draw(screen, room, _field((10, 10, L.LIT)))
    assert _cell(screen, 10, 10) == (0,) * 8


def test_a_session_collects_the_gratings_once_and_draws_them():
    """The played path: a room's grating cells are read from the map when
    the place is made, and reach `floor.draw`. The playtest building has
    none yet, so this is checked on the session's own reading of a room
    that does."""
    from spikes import session as session_mod
    room = building.Room("scratch", _blank_room(
        at={(10, 10): building.GRATING, (12, 10): building.GRATING}).rows,
        ink=building.palette(WHITE), player_start=(5, 5))
    place = session_mod.Place(0, room, [], beam_seed=1)
    assert place.grating_cells == {(10, 10), (12, 10)}


# --- the gallery ------------------------------------------------------------

def test_the_furniture_sheet_shows_every_kind_lit_and_dim():
    """Read back off the screen, from the game's own tables, so a sheet
    drawn from a second copy could not agree with itself and disagree with
    the game."""
    screen = Screen()
    gallery.draw_furniture_sheet(screen)
    shown = [kind for kind, _caption in gallery.FURNITURE_CAPTIONS]
    assert shown == list(building.FURNITURE)
    for n, kind in enumerate(shown):
        cy = gallery._FURNITURE_TOP + n
        assert _cell(screen, gallery._LIT_COL, cy) == tiles.FURNITURE[kind]
        assert _cell(screen, gallery._DIM_COL, cy) == tiles.FURNITURE_DIM[kind]


def test_the_furniture_plan_has_every_kind_on_a_solid_or_floor_cell():
    """The sheet's plan is held to the rooms' rule: every solid piece where
    the plan would otherwise be wall, so its walls join up; every grating on
    floor. And every kind is in it, once at least."""
    chars = "".join(gallery.FURNITURE_PLAN)
    for kind in building.FURNITURE:
        assert kind in chars, kind
    assert building.DESK_L + building.DESK_R in chars, \
        "the desk's halves are authored side by side"
    screen = Screen()
    gallery.draw_furniture_sheet(screen)
    top = gallery._FURNITURE_PLAN_LIT_TOP
    for cy, row in enumerate(gallery.FURNITURE_PLAN):
        for cx, char in enumerate(row):
            if char in building.SOLID_FURNITURE:
                assert _cell(screen, cx, top + cy) == tiles.FURNITURE[char]
            elif char == building.WALL:
                mask = tiles.mask_at(gallery.furniture_plan_is_wall, cx, cy)
                assert _cell(screen, cx, top + cy) == tiles.WALL_LIT[mask]
            elif char == building.GRATING:
                assert _cell(screen, cx, top + cy) == \
                    tiles.FURNITURE[building.GRATING]


# --- the geometry has not moved ---------------------------------------------

@pytest.mark.parametrize("name", list(STORED_SOLIDITY))
def test_each_rooms_solidity_is_the_stored_copy(name):
    """**The pin that makes this slice log-identical by construction.** A
    solid piece re-skins a cell that was already solid, so nothing that
    consults `is_solid` -- collision, steering, the swarm's reach, the fade
    -- can tell it was placed. A piece on floor would change this bitmap,
    and this test, and the difficulty targets with them."""
    room = scene.BUILDING[scene.BUILDING.index_of(name)]
    got = _solidity(room)
    assert got == STORED_SOLIDITY[name], "\n".join(
        f"{a}   {b}" for a, b in zip(got, STORED_SOLIDITY[name]))


def test_every_solid_piece_in_a_room_map_sits_on_a_stored_solid_cell():
    """The same claim read off the map characters rather than the bitmap,
    so that a room can be checked against a copy taken before the furniture
    went in: solid furniture only where the copy has `#`, gratings only where
    it has `.`."""
    for room in scene.BUILDING.rooms:
        stored = STORED_SOLIDITY[room.name]
        for cy, row in enumerate(room.rows):
            for cx, char in enumerate(row):
                if char in building.SOLID_FURNITURE:
                    assert stored[cy][cx] == "#", (room.name, cx, cy, char)
                elif char == building.GRATING:
                    assert stored[cy][cx] == ".", (room.name, cx, cy, char)


def test_the_solid_cell_counts_are_what_they_were():
    """The two numbers the repaint comparison was taken against, unchanged:
    a re-skinned wall is still a wall."""
    counts = {r.name: sum(r.solid_map()) for r in scene.BUILDING.rooms}
    assert counts == {scene.NEAR_NAME: 151, scene.FAR_NAME: 157}
    assert counts == {name: sum(row.count("#") for row in rows)
                      for name, rows in STORED_SOLIDITY.items()}
