; Bitmaps, generated by tools/bitmaps.py. Do not edit.
;
; Source: assets/sprites, assets/tiles. Regenerate with::
;
;     python tools/bitmaps.py --asm <this file> assets/sprites assets/tiles
;
; Bit 7 is the leftmost pixel, one byte per row, rows top to bottom.
; No timestamp: the file is committed and a test compares it byte for
; byte, so any diff is art and code having drifted.

BODY:
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $60                   ; .##.....   the head, rolled off the centre line
        DEFB $F0                   ; ####....
        DEFB $70                   ; .###....
        DEFB $38                   ; ..###...   shoulders
        DEFB $3F                   ; ..######   one arm flung out
        DEFB $38                   ; ..###...   trunk
        DEFB $F8                   ; #####...   the other arm, lower and bent
        DEFB $38                   ; ..###...
        DEFB $38                   ; ..###...
        DEFB $38                   ; ..###...
        DEFB $7C                   ; .#####..   hips
        DEFB $C6                   ; ##...##.   legs, splayed unevenly
        DEFB $83                   ; #.....##
        DEFB $00                   ; ........

CLEG:
        DEFB $00                   ; ........
        DEFB $42                   ; .#....#.   legs out
        DEFB $24                   ; ..#..#..
        DEFB $7E                   ; .######.   body
        DEFB $FF                   ; ########
        DEFB $7E                   ; .######.
        DEFB $24                   ; ..#..#..   legs
        DEFB $42                   ; .#....#.

DOORWAY_00:
        DEFB $00                   ; ........   mask  0, -
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

DOORWAY_01:
        DEFB $C3                   ; ##....##   mask  1, N
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

DOORWAY_02:
        DEFB $01                   ; .......#   mask  2, E
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

DOORWAY_03:
        DEFB $C3                   ; ##....##   mask  3, NE
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

DOORWAY_04:
        DEFB $00                   ; ........   mask  4, S
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##

DOORWAY_05:
        DEFB $C3                   ; ##....##   mask  5, NS
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##

DOORWAY_06:
        DEFB $01                   ; .......#   mask  6, ES
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $C3                   ; ##....##

DOORWAY_07:
        DEFB $C3                   ; ##....##   mask  7, NES
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $C3                   ; ##....##

DOORWAY_08:
        DEFB $80                   ; #.......   mask  8, W
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

DOORWAY_09:
        DEFB $C3                   ; ##....##   mask  9, NW
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

DOORWAY_10:
        DEFB $81                   ; #......#   mask 10, EW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

DOORWAY_11:
        DEFB $C3                   ; ##....##   mask 11, NEW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

DOORWAY_12:
        DEFB $80                   ; #.......   mask 12, SW
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $C3                   ; ##....##

DOORWAY_13:
        DEFB $C3                   ; ##....##   mask 13, NSW
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $C3                   ; ##....##

DOORWAY_14:
        DEFB $81                   ; #......#   mask 14, ESW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $C3                   ; ##....##

DOORWAY_15:
        DEFB $C3                   ; ##....##   mask 15, NESW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $C3                   ; ##....##

FOLLOWER:
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $3C                   ; ..####..   head
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   shoulders
        DEFB $7E                   ; .######.
        DEFB $5A                   ; .#.##.#.   arms down at the sides
        DEFB $5A                   ; .#.##.#.
        DEFB $5A                   ; .#.##.#.
        DEFB $3C                   ; ..####..   hips
        DEFB $24                   ; ..#..#..   legs
        DEFB $24                   ; ..#..#..
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

KEY:
        DEFB $00                   ; ........
        DEFB $1C                   ; ...###..   ring
        DEFB $22                   ; ..#...#.
        DEFB $22                   ; ..#...#.
        DEFB $1C                   ; ...###..
        DEFB $08                   ; ....#...   shaft
        DEFB $0E                   ; ....###.   teeth
        DEFB $00                   ; ........

LAMP:
        DEFB $00                   ; ........
        DEFB $18                   ; ...##...   handle
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   dome
        DEFB $FF                   ; ########   lens
        DEFB $66                   ; .##..##.   beam
        DEFB $24                   ; ..#..#..
        DEFB $00                   ; ........

NEST:
        DEFB $00                   ; ........
        DEFB $FF                   ; ########   rim
        DEFB $81                   ; #......#
        DEFB $BD                   ; #.####.#   something inside
        DEFB $BD                   ; #.####.#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $00                   ; ........

PLAYER:
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $3C                   ; ..####..   head, seen from above - no hat, no face
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $FF                   ; ########   shoulders, full width - the kit
        DEFB $FF                   ; ########
        DEFB $DB                   ; ##.##.##   arms clear of the body
        DEFB $DB                   ; ##.##.##
        DEFB $DB                   ; ##.##.##
        DEFB $7E                   ; .######.   hips
        DEFB $66                   ; .##..##.   legs, planted wide
        DEFB $66                   ; .##..##.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WALL_DIM_00:
        DEFB $FF                   ; ########   mask  0, -
        DEFB $FF                   ; ########
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_DIM_01:
        DEFB $81                   ; #......#   mask  1, N
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_DIM_02:
        DEFB $FF                   ; ########   mask  2, E
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $FF                   ; ########

WALL_DIM_03:
        DEFB $80                   ; #.......   mask  3, NE
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $FF                   ; ########

WALL_DIM_04:
        DEFB $FF                   ; ########   mask  4, S
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

WALL_DIM_05:
        DEFB $81                   ; #......#   mask  5, NS
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

WALL_DIM_06:
        DEFB $FF                   ; ########   mask  6, ES
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

WALL_DIM_07:
        DEFB $80                   ; #.......   mask  7, NES
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

WALL_DIM_08:
        DEFB $FF                   ; ########   mask  8, W
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $FF                   ; ########

WALL_DIM_09:
        DEFB $01                   ; .......#   mask  9, NW
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########

WALL_DIM_10:
        DEFB $FF                   ; ########   mask 10, EW
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $FF                   ; ########

WALL_DIM_11:
        DEFB $00                   ; ........   mask 11, NEW
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $FF                   ; ########

WALL_DIM_12:
        DEFB $FF                   ; ########   mask 12, SW
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

WALL_DIM_13:
        DEFB $01                   ; .......#   mask 13, NSW
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

WALL_DIM_14:
        DEFB $FF                   ; ########   mask 14, ESW
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WALL_DIM_15:
        DEFB $00                   ; ........   mask 15, NESW
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WALL_LIT_00:
        DEFB $FF                   ; ########   mask  0, -
        DEFB $FF                   ; ########
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_LIT_01:
        DEFB $91                   ; #..#...#   mask  1, N
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_LIT_02:
        DEFB $FF                   ; ########   mask  2, E
        DEFB $FF                   ; ########
        DEFB $C1                   ; ##.....#
        DEFB $C1                   ; ##.....#
        DEFB $C1                   ; ##.....#
        DEFB $FF                   ; ########
        DEFB $D0                   ; ##.#....
        DEFB $FF                   ; ########

WALL_LIT_03:
        DEFB $90                   ; #..#....   mask  3, NE
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $90                   ; #..#....
        DEFB $FF                   ; ########

WALL_LIT_04:
        DEFB $FF                   ; ########   mask  4, S
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $91                   ; #..#...#
        DEFB $91                   ; #..#...#

WALL_LIT_05:
        DEFB $91                   ; #..#...#   mask  5, NS
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $91                   ; #..#...#
        DEFB $91                   ; #..#...#

WALL_LIT_06:
        DEFB $FF                   ; ########   mask  6, ES
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $90                   ; #..#....
        DEFB $90                   ; #..#....

WALL_LIT_07:
        DEFB $90                   ; #..#....   mask  7, NES
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $90                   ; #..#....
        DEFB $90                   ; #..#....

WALL_LIT_08:
        DEFB $FF                   ; ########   mask  8, W
        DEFB $FF                   ; ########
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $FF                   ; ########
        DEFB $13                   ; ...#..##
        DEFB $FF                   ; ########

WALL_LIT_09:
        DEFB $11                   ; ...#...#   mask  9, NW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $11                   ; ...#...#
        DEFB $FF                   ; ########

WALL_LIT_10:
        DEFB $FF                   ; ########   mask 10, EW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $FF                   ; ########

WALL_LIT_11:
        DEFB $10                   ; ...#....   mask 11, NEW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $FF                   ; ########

WALL_LIT_12:
        DEFB $FF                   ; ########   mask 12, SW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $11                   ; ...#...#
        DEFB $11                   ; ...#...#

WALL_LIT_13:
        DEFB $11                   ; ...#...#   mask 13, NSW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $11                   ; ...#...#
        DEFB $11                   ; ...#...#

WALL_LIT_14:
        DEFB $FF                   ; ########   mask 14, ESW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $10                   ; ...#....

WALL_LIT_15:
        DEFB $10                   ; ...#....   mask 15, NESW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $10                   ; ...#....

WORKER:
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##   hands, raised clear of the shoulders
        DEFB $C3                   ; ##....##
        DEFB $99                   ; #..##..#   arms, and the crown of the head between them
        DEFB $BD                   ; #.####.#   head
        DEFB $7E                   ; .######.   shoulders - narrower than the player's
        DEFB $7E                   ; .######.
        DEFB $3C                   ; ..####..   trunk
        DEFB $3C                   ; ..####..
        DEFB $24                   ; ..#..#..   legs, foreshortened
        DEFB $24                   ; ..#..#..
        DEFB $24                   ; ..#..#..
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
