; Bitmaps, generated by tools/bitmaps.py. Do not edit.
;
; Source: assets/sprites, assets/tiles. Regenerate with::
;
;     python tools/bitmaps.py --asm <this file> assets/sprites assets/tiles
;
; Bit 7 is the leftmost pixel, rows top to bottom, one byte per eight
; pixels -- so a 16-wide row is two bytes, left cell first.
; Every sprite is followed by NAME_MASK: its ink dilated one pixel,
; clipped to the box, a set bit being a pixel to clear. The sprite
; routine's AND-mask is the complement, taken when the rotations are
; built, so that this file and the Python hold the same bytes.
; No timestamp: the file is committed and a test compares it byte for
; byte, so any diff is art and code having drifted.

BATTEN:
        DEFB $00                   ; ........   a strip light seen from above, not an octagon
        DEFB $00                   ; ........
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $00                   ; ........
        DEFB $00                   ; ........

BATTEN_MASK:
        DEFB $00                   ; ........
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $00                   ; ........

BODY:
        DEFB $03,$00               ; ......##........   the arm, flung back over the head
        DEFB $3D,$00               ; ..####.#........
        DEFB $7E,$F0               ; .######.####....   the head, off the axis, and a shoulder
        DEFB $7D,$FF               ; .#####.#########   the trunk, lying across the join
        DEFB $3B,$FF               ; ..###.##########
        DEFB $03,$DC               ; ......####.###..   hips, and one leg trailing
        DEFB $00,$63               ; .........##...##   the other leg, splayed differently
        DEFB $00,$00               ; ................

BODY_MASK:
        DEFB $7F,$80               ; .########.......
        DEFB $FF,$F8               ; #############...
        DEFB $FF,$FF               ; ################
        DEFB $FF,$FF               ; ################
        DEFB $FF,$FF               ; ################
        DEFB $7F,$FF               ; .###############
        DEFB $07,$FF               ; .....###########
        DEFB $00,$F7               ; ........####.###

CLEG_A:
        DEFB $00                   ; ........
        DEFB $18                   ; ...##...   head
        DEFB $FF                   ; ########   wings out, the whole width
        DEFB $FF                   ; ########
        DEFB $18                   ; ...##...   body
        DEFB $18                   ; ...##...
        DEFB $18                   ; ...##...
        DEFB $42                   ; .#....#.   legs

CLEG_A_MASK:
        DEFB $3C                   ; ..####..
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $3C                   ; ..####..
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

CLEG_B:
        DEFB $00                   ; ........
        DEFB $18                   ; ...##...   head, unchanged
        DEFB $3C                   ; ..####..   thorax, the wing roots
        DEFB $5A                   ; .#.##.#.   wings swept back along the body
        DEFB $5A                   ; .#.##.#.
        DEFB $99                   ; #..##..#
        DEFB $81                   ; #......#   wingtips, past the abdomen
        DEFB $24                   ; ..#..#..   legs, tucked

CLEG_B_MASK:
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

DOORWAY_00:
        DEFB $00                   ; ........   mask  0, -
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

DOORWAY_01:
        DEFB $C3                   ; ##....##   mask  1, N
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

DOORWAY_02:
        DEFB $01                   ; .......#   mask  2, E
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

DOORWAY_03:
        DEFB $C3                   ; ##....##   mask  3, NE
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

DOORWAY_04:
        DEFB $00                   ; ........   mask  4, S
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##

DOORWAY_05:
        DEFB $C3                   ; ##....##   mask  5, NS
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##

DOORWAY_06:
        DEFB $01                   ; .......#   mask  6, ES
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $C3                   ; ##....##

DOORWAY_07:
        DEFB $C3                   ; ##....##   mask  7, NES
        DEFB $01                   ; .......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $01                   ; .......#
        DEFB $C3                   ; ##....##

DOORWAY_08:
        DEFB $80                   ; #.......   mask  8, W
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

DOORWAY_09:
        DEFB $C3                   ; ##....##   mask  9, NW
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

DOORWAY_10:
        DEFB $81                   ; #......#   mask 10, EW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

DOORWAY_11:
        DEFB $C3                   ; ##....##   mask 11, NEW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

DOORWAY_12:
        DEFB $80                   ; #.......   mask 12, SW
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $C3                   ; ##....##

DOORWAY_13:
        DEFB $C3                   ; ##....##   mask 13, NSW
        DEFB $80                   ; #.......
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $80                   ; #.......
        DEFB $C3                   ; ##....##

DOORWAY_14:
        DEFB $81                   ; #......#   mask 14, ESW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $C3                   ; ##....##

DOORWAY_15:
        DEFB $C3                   ; ##....##   mask 15, NESW
        DEFB $81                   ; #......#
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $81                   ; #......#
        DEFB $C3                   ; ##....##

DOOR_LOCKED:
        DEFB $FF                   ; ########   a closed frame
        DEFB $81                   ; #......#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $A5                   ; #.#..#.#   the keyhole
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $BD                   ; #.####.#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########

DOOR_LOCKED_MASK:
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

DOOR_OPEN:
        DEFB $C3                   ; ##....##   two jambs, a four-pixel gap
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##   no head and no sill: open at both ends

DOOR_OPEN_MASK:
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###

FLOOR_DIM:
        DEFB $00                   ; ........   one dot in sixty-four -- ground you are remembering, not seeing
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $10                   ; ...#....
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

FLOOR_LIT:
        DEFB $00                   ; ........   four dots, evenly spread -- fully lit ground
        DEFB $44                   ; .#...#..
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $44                   ; .#...#..
        DEFB $00                   ; ........
        DEFB $00                   ; ........

FOLLOWER_A:
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $18                   ; ...##...   head, a disc
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   shoulders
        DEFB $7E                   ; .######.
        DEFB $58                   ; .#.##...   hands beside the hips, swinging
        DEFB $1A                   ; ...##.#.
        DEFB $0C                   ; ....##..   feet
        DEFB $30                   ; ..##....
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

FOLLOWER_A_MASK:
        DEFB $00                   ; ........
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $7F                   ; .#######
        DEFB $7E                   ; .######.
        DEFB $78                   ; .####...
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

FOLLOWER_B:
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $18                   ; ...##...   head
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   shoulders
        DEFB $7E                   ; .######.
        DEFB $1A                   ; ...##.#.   frame A in the mirror
        DEFB $58                   ; .#.##...
        DEFB $30                   ; ..##....   feet swapped
        DEFB $0C                   ; ....##..
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

FOLLOWER_B_MASK:
        DEFB $00                   ; ........
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FE                   ; #######.
        DEFB $7E                   ; .######.
        DEFB $1E                   ; ...####.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

HOUSING:
        DEFB $3C                   ; ..####..   a ring with a lens: the searchlight, bolted down
        DEFB $42                   ; .#....#.
        DEFB $81                   ; #......#
        DEFB $99                   ; #..##..#
        DEFB $99                   ; #..##..#
        DEFB $81                   ; #......#
        DEFB $42                   ; .#....#.
        DEFB $3C                   ; ..####..

HOUSING_MASK:
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

KEY:
        DEFB $00                   ; ........
        DEFB $1C                   ; ...###..   ring
        DEFB $22                   ; ..#...#.
        DEFB $22                   ; ..#...#.
        DEFB $1C                   ; ...###..
        DEFB $08                   ; ....#...   shaft
        DEFB $0E                   ; ....###.   teeth
        DEFB $00                   ; ........

KEY_MASK:
        DEFB $3E                   ; ..#####.
        DEFB $7F                   ; .#######
        DEFB $7F                   ; .#######
        DEFB $7F                   ; .#######
        DEFB $7F                   ; .#######
        DEFB $3F                   ; ..######
        DEFB $1F                   ; ...#####
        DEFB $1F                   ; ...#####

LAMP_OFF:
        DEFB $3C                   ; ..####..   a hollow octagon: a spotlight lying dark
        DEFB $42                   ; .#....#.
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $42                   ; .#....#.
        DEFB $3C                   ; ..####..

LAMP_OFF_MASK:
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $E7                   ; ###..###
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $E7                   ; ###..###
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

LAMP_ON:
        DEFB $3C                   ; ..####..   filled: the same spotlight burning
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $7E                   ; .######.
        DEFB $3C                   ; ..####..

LAMP_ON_MASK:
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

NEST:
        DEFB $00                   ; ........
        DEFB $30                   ; ..##....   the lip, broken and off-centre
        DEFB $7C                   ; .#####..
        DEFB $FE                   ; #######.
        DEFB $DF                   ; ##.#####   the brood, uneven
        DEFB $FF                   ; ########
        DEFB $7E                   ; .######.
        DEFB $2C                   ; ..#.##..   it does not sit square

NEST_MASK:
        DEFB $78                   ; .####...
        DEFB $FE                   ; #######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

PLAYER_A:
        DEFB $00                   ; ........
        DEFB $3C                   ; ..####..   the lamp, worn on the helmet
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   helmet, a disc four rows deep
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########   shoulders, full width - the kit
        DEFB $FF                   ; ########
        DEFB $BC                   ; #.####..   a hand forward, beside the hip
        DEFB $19                   ; ...##..#   the other hand, swung back
        DEFB $0C                   ; ....##..   a foot out from under
        DEFB $30                   ; ..##....   the other, behind
        DEFB $00                   ; ........   one clear row, so the mark is not feet
        DEFB $FF                   ; ########   the mark: the only figure with ground under him
        DEFB $FF                   ; ########

PLAYER_A_MASK:
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $7F                   ; .#######
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

PLAYER_B:
        DEFB $00                   ; ........
        DEFB $3C                   ; ..####..   the lamp
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   helmet
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########   shoulders
        DEFB $FF                   ; ########
        DEFB $3D                   ; ..####.#   frame A in the mirror: the other hand forward
        DEFB $98                   ; #..##...
        DEFB $30                   ; ..##....   feet swapped
        DEFB $0C                   ; ....##..
        DEFB $00                   ; ........
        DEFB $FF                   ; ########   the mark
        DEFB $FF                   ; ########

PLAYER_B_MASK:
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FE                   ; #######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

SPRAY:
        DEFB $00                   ; ........   scattered droplets, staggered so they are not the floor's columns
        DEFB $22                   ; ..#...#.
        DEFB $00                   ; ........
        DEFB $88                   ; #...#...
        DEFB $00                   ; ........
        DEFB $22                   ; ..#...#.
        DEFB $00                   ; ........
        DEFB $88                   ; #...#...

WALL_DIM_00:
        DEFB $FF                   ; ########   mask  0, -
        DEFB $FF                   ; ########
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $EB                   ; ###.#.##
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_DIM_01:
        DEFB $81                   ; #......#   mask  1, N
        DEFB $AB                   ; #.#.#.##
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $AB                   ; #.#.#.##
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_DIM_02:
        DEFB $FF                   ; ########   mask  2, E
        DEFB $EA                   ; ###.#.#.
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $EA                   ; ###.#.#.
        DEFB $C0                   ; ##......
        DEFB $FF                   ; ########

WALL_DIM_03:
        DEFB $80                   ; #.......   mask  3, NE
        DEFB $AA                   ; #.#.#.#.
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $AA                   ; #.#.#.#.
        DEFB $80                   ; #.......
        DEFB $FF                   ; ########

WALL_DIM_04:
        DEFB $FF                   ; ########   mask  4, S
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $AB                   ; #.#.#.##
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

WALL_DIM_05:
        DEFB $81                   ; #......#   mask  5, NS
        DEFB $AB                   ; #.#.#.##
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $AB                   ; #.#.#.##
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#

WALL_DIM_06:
        DEFB $FF                   ; ########   mask  6, ES
        DEFB $AA                   ; #.#.#.#.
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $AA                   ; #.#.#.#.
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

WALL_DIM_07:
        DEFB $80                   ; #.......   mask  7, NES
        DEFB $AA                   ; #.#.#.#.
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......
        DEFB $AA                   ; #.#.#.#.
        DEFB $80                   ; #.......
        DEFB $80                   ; #.......

WALL_DIM_08:
        DEFB $FF                   ; ########   mask  8, W
        DEFB $AB                   ; #.#.#.##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $AB                   ; #.#.#.##
        DEFB $03                   ; ......##
        DEFB $FF                   ; ########

WALL_DIM_09:
        DEFB $01                   ; .......#   mask  9, NW
        DEFB $AB                   ; #.#.#.##
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $AB                   ; #.#.#.##
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########

WALL_DIM_10:
        DEFB $FF                   ; ########   mask 10, EW
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $FF                   ; ########

WALL_DIM_11:
        DEFB $00                   ; ........   mask 11, NEW
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $FF                   ; ########

WALL_DIM_12:
        DEFB $FF                   ; ########   mask 12, SW
        DEFB $AB                   ; #.#.#.##
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $AB                   ; #.#.#.##
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

WALL_DIM_13:
        DEFB $01                   ; .......#   mask 13, NSW
        DEFB $AB                   ; #.#.#.##
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $AB                   ; #.#.#.##
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#

WALL_DIM_14:
        DEFB $FF                   ; ########   mask 14, ESW
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WALL_DIM_15:
        DEFB $00                   ; ........   mask 15, NESW
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $AA                   ; #.#.#.#.
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WALL_LIT_00:
        DEFB $FF                   ; ########   mask  0, -
        DEFB $FF                   ; ########
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_LIT_01:
        DEFB $91                   ; #..#...#   mask  1, N
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########

WALL_LIT_02:
        DEFB $FF                   ; ########   mask  2, E
        DEFB $FF                   ; ########
        DEFB $C1                   ; ##.....#
        DEFB $C1                   ; ##.....#
        DEFB $C1                   ; ##.....#
        DEFB $FF                   ; ########
        DEFB $D0                   ; ##.#....
        DEFB $FF                   ; ########

WALL_LIT_03:
        DEFB $90                   ; #..#....   mask  3, NE
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $90                   ; #..#....
        DEFB $FF                   ; ########

WALL_LIT_04:
        DEFB $FF                   ; ########   mask  4, S
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $91                   ; #..#...#
        DEFB $91                   ; #..#...#

WALL_LIT_05:
        DEFB $91                   ; #..#...#   mask  5, NS
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $91                   ; #..#...#
        DEFB $91                   ; #..#...#

WALL_LIT_06:
        DEFB $FF                   ; ########   mask  6, ES
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $90                   ; #..#....
        DEFB $90                   ; #..#....

WALL_LIT_07:
        DEFB $90                   ; #..#....   mask  7, NES
        DEFB $FF                   ; ########
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $81                   ; #......#
        DEFB $FF                   ; ########
        DEFB $90                   ; #..#....
        DEFB $90                   ; #..#....

WALL_LIT_08:
        DEFB $FF                   ; ########   mask  8, W
        DEFB $FF                   ; ########
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $FF                   ; ########
        DEFB $13                   ; ...#..##
        DEFB $FF                   ; ########

WALL_LIT_09:
        DEFB $11                   ; ...#...#   mask  9, NW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $11                   ; ...#...#
        DEFB $FF                   ; ########

WALL_LIT_10:
        DEFB $FF                   ; ########   mask 10, EW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $FF                   ; ########

WALL_LIT_11:
        DEFB $10                   ; ...#....   mask 11, NEW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $FF                   ; ########

WALL_LIT_12:
        DEFB $FF                   ; ########   mask 12, SW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $11                   ; ...#...#
        DEFB $11                   ; ...#...#

WALL_LIT_13:
        DEFB $11                   ; ...#...#   mask 13, NSW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $11                   ; ...#...#
        DEFB $11                   ; ...#...#

WALL_LIT_14:
        DEFB $FF                   ; ########   mask 14, ESW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $10                   ; ...#....

WALL_LIT_15:
        DEFB $10                   ; ...#....   mask 15, NESW
        DEFB $FF                   ; ########
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $01                   ; .......#
        DEFB $FF                   ; ########
        DEFB $10                   ; ...#....
        DEFB $10                   ; ...#....

WORKER_A:
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##   hands, raised beside the crown
        DEFB $C3                   ; ##....##
        DEFB $18                   ; ...##...   head, a row lower than the follower's
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   shoulders
        DEFB $7E                   ; .######.
        DEFB $18                   ; ...##...   hips - the arms are up, so no hands here
        DEFB $18                   ; ...##...
        DEFB $0C                   ; ....##..   feet
        DEFB $30                   ; ..##....
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WORKER_A_MASK:
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $3E                   ; ..#####.
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $78                   ; .####...
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WORKER_B:
        DEFB $00                   ; ........
        DEFB $C3                   ; ##....##   hands, raised
        DEFB $C3                   ; ##....##
        DEFB $18                   ; ...##...   head
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.   shoulders
        DEFB $7E                   ; .######.
        DEFB $18                   ; ...##...   hips
        DEFB $18                   ; ...##...
        DEFB $30                   ; ..##....   feet swapped
        DEFB $0C                   ; ....##..
        DEFB $00                   ; ........
        DEFB $00                   ; ........
        DEFB $00                   ; ........

WORKER_B_MASK:
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $7C                   ; .#####..
        DEFB $7E                   ; .######.
        DEFB $7E                   ; .######.
        DEFB $1E                   ; ...####.
        DEFB $00                   ; ........
        DEFB $00                   ; ........
