; Bitmaps, generated by tools/bitmaps.py. Do not edit.
;
; Source: assets/logo. Regenerate with::
;
;     python tools/bitmaps.py --asm <this file> assets/logo
;
; Bit 7 is the leftmost pixel, one byte per row, rows top to bottom.
; No timestamp: the file is committed and a test compares it byte for
; byte, so any diff is art and code having drifted.

LOGO_G:
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.
        DEFB $E7                   ; ###..###
        DEFB $C3                   ; ##....##
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $C0                   ; ##......
        DEFB $CF                   ; ##..####   the spur, which is the whole difference from O
        DEFB $CF                   ; ##..####
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $E7                   ; ###..###
        DEFB $7E                   ; .######.
        DEFB $3C                   ; ..####..
        DEFB $00                   ; ........

LOGO_H:
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $FF                   ; ########   the crossbar, on the seam between the two cell rows
        DEFB $FF                   ; ########
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $00                   ; ........

LOGO_I:
        DEFB $FF                   ; ########   serifed top and bottom, or it would read as the stem of a T
        DEFB $FF                   ; ########
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $FF                   ; ########
        DEFB $FF                   ; ########
        DEFB $00                   ; ........

LOGO_L:
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $FF                   ; ########   the foot, and it reaches the full width like T's arm
        DEFB $FF                   ; ########
        DEFB $00                   ; ........

LOGO_O:
        DEFB $3C                   ; ..####..
        DEFB $7E                   ; .######.
        DEFB $E7                   ; ###..###
        DEFB $C3                   ; ##....##   two-pixel sides, so the counter stays open at 1:1
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $C3                   ; ##....##
        DEFB $E7                   ; ###..###
        DEFB $7E                   ; .######.
        DEFB $3C                   ; ..####..
        DEFB $00                   ; ........

LOGO_P:
        DEFB $FC                   ; ######..
        DEFB $FE                   ; #######.
        DEFB $E7                   ; ###..###
        DEFB $E3                   ; ###...##
        DEFB $E3                   ; ###...##
        DEFB $E7                   ; ###..###
        DEFB $FE                   ; #######.
        DEFB $FC                   ; ######..   the bowl closes here
        DEFB $E0                   ; ###.....   and the stem runs the rest of the way down
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $00                   ; ........

LOGO_S:
        DEFB $3C                   ; ..####..   the top curve, three pixels thick
        DEFB $7E                   ; .######.
        DEFB $E7                   ; ###..###
        DEFB $E0                   ; ###.....
        DEFB $E0                   ; ###.....
        DEFB $F0                   ; ####....   the waist turns back on itself
        DEFB $7C                   ; .#####..
        DEFB $3E                   ; ..#####.
        DEFB $07                   ; .....###   and comes down the other side
        DEFB $03                   ; ......##
        DEFB $03                   ; ......##
        DEFB $E7                   ; ###..###
        DEFB $E7                   ; ###..###
        DEFB $7E                   ; .######.
        DEFB $3C                   ; ..####..
        DEFB $00                   ; ........   the baseline row every glyph ends on

LOGO_T:
        DEFB $FF                   ; ########   a full-width arm -- the spacing is the blank cell either side
        DEFB $FF                   ; ########
        DEFB $3C                   ; ..####..   a four-pixel stem, centred
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $3C                   ; ..####..
        DEFB $00                   ; ........
