#!/usr/bin/env python3
"""A room's **solidity bitmap**, generated for the Z80 from the authored shell.

The same decision as `bitmaps.py` and for the same reasons (*2026-09-10 The
asset pipeline*): the shell is authored as a grid of `#` and `.` in
`assets/levels/`, and every table either machine reads is generated from it. A
hand-kept copy of a room would drift from the one the prototype plays.

**What the port needs from a room is one bit a cell: solid, or not.** That is
what `tiles.mask_at` asks of it -- four bit tests for the four neighbours, to
pick which of the sixteen wall tiles a cell wears -- and its docstring already
costed the Z80 version at *"four bit tests against an 88-byte solidity bitmap
with an implicit solid border, about 120 T-states"*. This emits exactly that
bitmap:

* **22 rows of 4 bytes**, the play area's own height and width, 88 bytes a room.
* **Bit 7 is the leftmost cell** of each byte, which is `bitmaps.py`'s rule for
  pixels applied to cells, so nothing anywhere reverses a bit order.
* **A set bit is solid.** Walls and the shell's own internal structure; floor is
  clear.
* **The border off the grid is solid by implication** and is not stored. The
  predicate has to answer True off the room -- that is what makes the outer wall
  show one face, inward -- and `Room.is_wall` does, so the port's reader does
  too rather than storing a ring of bits it can infer.

Issue #153. Deterministic, no timestamp: the file is committed and a test
regenerates it and compares byte for byte, so any diff is the level and the port
having drifted.
"""

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "prototype"))

from spikes import building as B, levels          # noqa: E402
from spikes.layout import PLAY_ROWS               # noqa: E402
from spotlight.core.constants import COLS         # noqa: E402

#: Bytes a row: 32 cells, eight to a byte.
ROW_BYTES = COLS // 8


def shell_rows(path: pathlib.Path, name: str) -> tuple[str, ...]:
    """The named `shape:` block from a level file, as its authored rows."""
    _n, _title, _specs, _budget, shapes = levels.parse(path.read_text())
    if name not in shapes:
        raise SystemExit(f"{path.name} has no shape {name!r}; "
                         f"it has {', '.join(sorted(shapes))}")
    return shapes[name]


def pack(rows) -> list[list[int]]:
    """Each row as `ROW_BYTES` bytes, bit 7 the leftmost cell, set if solid."""
    if len(rows) != PLAY_ROWS:
        raise SystemExit(f"a shell is {PLAY_ROWS} rows, not {len(rows)}")
    out = []
    for row in rows:
        if len(row) != COLS:
            raise SystemExit(f"a row is {COLS} cells, not {len(row)}")
        packed = []
        for byte in range(ROW_BYTES):
            bits = 0
            for bit in range(8):
                if row[byte * 8 + bit] == B.WALL:
                    bits |= 0x80 >> bit
            packed.append(bits)
        out.append(packed)
    return out


def asm(name: str, rows, source: str) -> str:
    """The table, with each row's grid beside it so it stays reviewable."""
    label = name.upper().replace("-", "_")
    out = [
        f"; The solidity bitmap for shape `{name}`, generated by tools/rooms.py.",
        "; Do not edit.",
        ";",
        f"; Source: {source}",
        "; Regenerate with::",
        ";",
        f";     python tools/rooms.py {source} {name} --asm <this file>",
        ";",
        f"; {PLAY_ROWS} rows of {ROW_BYTES} bytes, bit 7 the leftmost cell, a set",
        "; bit solid. The border off the grid is solid by implication and is not",
        "; stored -- off the room counts as wall, which is what makes the outer",
        "; wall show one face.",
        "",
        f"{label}:",
    ]
    for packed, art in zip(pack(rows), rows):
        operand = "DEFB " + ",".join(f"${b:02X}" for b in packed)
        out.append(f"        {operand:<30s} ; {art}")
    out.append("")
    out.append(f"{label}_BYTES: EQU {PLAY_ROWS * ROW_BYTES}")
    out.append(f"{label}_STRIDE: EQU {ROW_BYTES}")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("level", help="a level file under assets/levels")
    parser.add_argument("shape", help="which authored shape: block to emit")
    parser.add_argument("--asm", dest="out", required=True,
                        help="write the Z80 DEFB table here")
    args = parser.parse_args(argv)
    path = pathlib.Path(args.level)
    rows = shell_rows(path, args.shape)
    text = asm(args.shape, rows, args.level)
    pathlib.Path(args.out).write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
